#!/bin/sh
echo "1: $1, 2: $2, 3: $3"
pid=$$
echo "pid: $pid"
echo "this is before the mark"
echo "***BEGIN***"
#echo "From: TESTING <stephen.shoecraft@hp.com>"
#echo "To: stephen.shoecraft@hp.com"
#echo "Subject: testing script output"
#echo ""
echo "start"
let i=0
while true
do
	echo "i: $i"
	sleep 1
	let i=$i+1
	test $i -ge 5 && break
done
echo "3 blanks follow"
echo ""
echo ""
echo ""
echo "done!"
#cat /home/shoecraf/src/patching/do_mtp_report_g3u0196c.houston.hp.com.log
echo "***END***"
echo "this is after the mark"
exit 2
