#!/bin/bash
v=`cat version.h | awk '{ print $3 }'`
eval ver=$v
rel=`cat release`
cat worker.spec.pre | sed "s:<VERSION>:$ver:" | sed "s:<RELEASE>:$rel:" > worker.spec
cat changelog >> worker.spec
exit 0
sudo rpmbuild -bb worker.spec
if [ $? -ne 0 ]; then
	exit 1
fi
rm -f worker.spec
let rel=$rel+1
echo $rel > release
