#!/bin/bash
test -z "$1" && exit 1
#if test `echo $1 | grep -c 'vm[0-9][0-9][0-9]$'` -gt 0; then
#if test `echo $1 | grep -c 'vm[0-9][0-9][0-9]$'` -gt 0; then
OPTS="-V"
if test `pwd` = "/home/sysadm/src/xplist"; then
SRC=./xplist
else
SRC=/usr/local/bin/xplist
fi
timeout 2 esxconf -a -s "$1" > /dev/null 2>&1
if test $? -eq 0; then
	/usr/local/bin/esxshell start $1
	/usr/local/lib/tools/esxcmd $1 "rm -f /tmp/xplist"
	/usr/local/lib/tools/esxscp $SRC $1:/tmp
	/usr/local/lib/tools/esxcmd $1 "/tmp/xplist $OPTS"
	/usr/local/bin/esxshell stop $1
else
	/usr/local/lib/tools/admssh $1 "sudo bash -c \"rm -f /tmp/xplist\""
	/usr/local/lib/tools/admscp $SRC $1:/tmp > /dev/null 2>&1
	test $? -ne 0 && exit 1
#	/usr/local/lib/tools/admssh $1 "sudo bash -c \"chmod 755 /tmp/xplist; /tmp/xplist -V; rm -f /tmp/xplist\""
	/usr/local/lib/tools/admssh $1 "sudo bash -c \"chmod 755 /tmp/xplist; /tmp/xplist $OPTS\""
fi
