
/*
*** this file is automatically generated - DO NOT MODIFY
*/

#include <stdio.h>
#include <string.h>
#include "gendb_vassetlocation.h"

int vassetlocation_fetch(DB *db) {
#if vassetlocation_field_count > 0
	SQLRETURN ret;

	dprintf("Fetching data...\n");
	ret = SQLFetch(db->hstmt);
	if (ret == SQL_SUCCESS || ret == SQL_SUCCESS_WITH_INFO) return 0;
	if (ret != 100) ret = dberr(SQL_HANDLE_STMT,db->hstmt,"vassetlocation_fetch");
	return ret;
#else
	return 0;
#endif
}

int vassetlocation_fetch_record(DB *db, struct vassetlocation_record *rec) {
#if vassetlocation_field_count > 0
	SQLRETURN ret;

	if ((ret = vassetlocation_fetch(db)) != 0) {
		SQLCloseCursor(db->hstmt);
		return ret;
	}
	memset(rec,0,sizeof(*rec));
	SQLGetData(db->hstmt, 1, SQL_C_BINARY, (SQLPOINTER) rec->_assetguid, sizeof(rec->_assetguid), 0);
	SQLGetData(db->hstmt, 2, SQL_C_BINARY, (SQLPOINTER) rec->_location, sizeof(rec->_location), 0);
	SQLGetData(db->hstmt, 3, SQL_C_CHAR, (SQLPOINTER) rec->asset_name, sizeof(rec->asset_name), 0);
	SQLGetData(db->hstmt, 4, SQL_C_CHAR, (SQLPOINTER) rec->location, sizeof(rec->location), 0);
	dprintf("----------------- vassetlocation record -----------------\n");
	dprintf("_assetguid          :  %x\n",rec->_assetguid);
	dprintf("_location           :  %x\n",rec->_location);
	dprintf("asset_name          :  %s\n",rec->asset_name);
	dprintf("location            :  %s\n",rec->location);
#endif
	return 0;
}

int vassetlocation_select(DB *db, char *clause) {
#if vassetlocation_field_count > 0
	char query[4096];
	SQLRETURN ret;

	sprintf(query,"SELECT vassetlocation._assetguid,vassetlocation._location,vassetlocation.asset_name,vassetlocation.location FROM vassetlocation %s",(clause ? clause : ""));
	dprintf("Executing query: %s\n", query);
	ret = SQLExecDirect(db->hstmt, (SQLCHAR *) query, SQL_NTS);
	if (ret == SQL_SUCCESS || ret == SQL_SUCCESS_WITH_INFO) return 0;
	ret = dberr(SQL_HANDLE_STMT,db->hstmt,"vassetlocation_select");
	return ret;
#else
	return 0;
#endif
}

int vassetlocation_select_record(DB *db, struct vassetlocation_record *rec, char *clause) {
#if vassetlocation_field_count > 0
	SQLRETURN ret;

	if ((ret = vassetlocation_select(db, clause)) != 0) return ret;
	if ((ret = vassetlocation_fetch_record(db, rec)) != 0) return ret;
	SQLCloseCursor(db->hstmt);
#endif
	return 0;
}

int vassetlocation_insert(DB *db, struct vassetlocation_record *rec) {
#if vassetlocation_field_count > 0
	char query[4096];
	SQLRETURN ret;

	sprintf(query,"INSERT INTO vassetlocation (_assetguid,_location,asset_name,location) VALUES (%x,%x,'%s','%s')",rec->_assetguid,rec->_location,rec->asset_name,rec->location);
	dprintf("Executing query: %s\n", query);
	ret = SQLExecDirect(db->hstmt, (SQLCHAR *) query, SQL_NTS);
	if (ret == SQL_SUCCESS || ret == SQL_SUCCESS_WITH_INFO) return 0;
	ret = dberr(SQL_HANDLE_STMT,db->hstmt,"vassetlocation_insert");
	printf("Offending query: %s\n", query);
	return ret;
#else
	return 0;
#endif
}

int vassetlocation_update_record(DB *db, struct vassetlocation_record *rec, char *clause) {
#if vassetlocation_field_count > 0
	char query[4096];
	SQLRETURN ret;

	sprintf(query,"UPDATE vassetlocation SET _assetguid = %x,_location = %x,asset_name = '%s',location = '%s'",rec->_assetguid,rec->_location,rec->asset_name,rec->location);
	if (clause) {
		if (clause[0] != ' ') strcat(query," ");
		strcat(query,clause);
	}
	dprintf("Executing query: %s\n", query);
	ret = SQLExecDirect(db->hstmt, (SQLCHAR *) query, SQL_NTS);
	if (ret == SQL_SUCCESS || ret == SQL_SUCCESS_WITH_INFO) return 0;
	ret = dberr(SQL_HANDLE_STMT,db->hstmt,"vassetlocation_update_record");
	return ret;
#else
	return 0;
#endif
}

int vassetlocation_delete(DB *db, char *clause) {
#if vassetlocation_field_count > 0
	char query[4096];
	SQLRETURN ret;

	sprintf(query,"DELETE FROM vassetlocation %s",(clause ? clause : ""));
	dprintf("Executing query: %s\n", query);
	ret = SQLExecDirect(db->hstmt, (SQLCHAR *) query, SQL_NTS);
	if (ret == SQL_SUCCESS || ret == SQL_SUCCESS_WITH_INFO) return 0;
	ret = dberr(SQL_HANDLE_STMT,db->hstmt,"vassetlocation_delete");
	return ret;
#else
	return 0;
#endif
}

