
#ifndef __VASSET_H
#define __VASSET_H

/*
*** this file is automatically generated - DO NOT MODIFY
*/

#include "db.h"

/* Structure definition for the vasset table */
struct vasset_record {
	unsigned char _resourceguid[36];
	unsigned char _resourcetypeguid[36];
	unsigned char _assetstatusguid[36];
	char asset_type[65];
	char status[251];
	char manufacturer[41];
	char model[101];
	char serial_number[101];
	char system_number[101];
	char barcode[101];
	char last_barcode_scan[24];
	char asset_tag[101];
};
#define vasset_field_count 12
int vasset_fetch(DB *db);
int vasset_fetch_record(DB *db, struct vasset_record *rec);
int vasset_select(DB *db, char *clause);
int vasset_select_record(DB *db, struct vasset_record *rec, char *clause);
int vasset_insert(DB *db, struct vasset_record *rec);
int vasset_update_record(DB *db, struct vasset_record *rec, char *clause);
int vasset_delete(DB *db, char *clause);

#endif /* __VASSET_H */
