
#ifndef __INV_USON_BACKUP_INFO_H
#define __INV_USON_BACKUP_INFO_H

/*
*** this file is automatically generated - DO NOT MODIFY
*/

#include "db.h"

/* Structure definition for the inv_uson_backup_info table */
struct inv_uson_backup_info_record {
	long long _id;
	unsigned char _resourceguid[36];
	char backup_method[51];
	char backup_ip[21];
	char detail_-_backup_method[101];
};
#define inv_uson_backup_info_field_count 5
int inv_uson_backup_info_fetch(DB *db);
int inv_uson_backup_info_fetch_record(DB *db, struct inv_uson_backup_info_record *rec);
int inv_uson_backup_info_select(DB *db, char *clause);
int inv_uson_backup_info_select_record(DB *db, struct inv_uson_backup_info_record *rec, char *clause);
int inv_uson_backup_info_insert(DB *db, struct inv_uson_backup_info_record *rec);
int inv_uson_backup_info_update_record(DB *db, struct inv_uson_backup_info_record *rec, char *clause);
int inv_uson_backup_info_delete(DB *db, char *clause);

#endif /* __INV_USON_BACKUP_INFO_H */
