
#ifndef ___VUSON_SERVICES_SYSTEMS_H
#define ___VUSON_SERVICES_SYSTEMS_H

/*
*** this file is automatically generated - DO NOT MODIFY
*/

#include "db.h"

/* Structure definition for the _vuson_services_systems table */
struct _vuson_services_systems_record {
	char services[251];
	char supporting_systems[251];
	unsigned char svcguid[36];
	unsigned char sysguid[36];
};
#define _vuson_services_systems_field_count 4
int _vuson_services_systems_fetch(DB *db);
int _vuson_services_systems_fetch_record(DB *db, struct _vuson_services_systems_record *rec);
int _vuson_services_systems_select(DB *db, char *clause);
int _vuson_services_systems_select_record(DB *db, struct _vuson_services_systems_record *rec, char *clause);
int _vuson_services_systems_insert(DB *db, struct _vuson_services_systems_record *rec);
int _vuson_services_systems_update_record(DB *db, struct _vuson_services_systems_record *rec, char *clause);
int _vuson_services_systems_delete(DB *db, char *clause);

#endif /* ___VUSON_SERVICES_SYSTEMS_H */
