
#ifndef __HOSTS_H
#define __HOSTS_H

/*
*** this file is automatically generated - DO NOT MODIFY
*/

#include "db.h"

/* Structure definition for the hosts table */
struct hosts_record {
	int id;
	int farm_id;
	char name[16384];
	char uuid[16384];
	char os[16384];
	char version[16384];
	int build;
	char model[16384];
	char serial[16384];
	char bios[16384];
	char status[16384];
	char in_maint[16384];
	float psp;
	int cpu_pkgs;
	int cpu_count;
	char cpu_model[16384];
	int cpu_total;
	int cpu_speed;
	int mem_total;
	int cons_mem;
	char subnet[16384];
	char last_seen[16384];
	char state[16384];
};
#define hosts_field_count 23
int hosts_fetch(DB *db);
int hosts_fetch_record(DB *db, struct hosts_record *rec);
int hosts_select(DB *db, char *clause);
int hosts_select_record(DB *db, struct hosts_record *rec, char *clause);
int hosts_insert(DB *db, struct hosts_record *rec);
int hosts_update_record(DB *db, struct hosts_record *rec, char *clause);
int hosts_delete(DB *db, char *clause);

#endif /* __HOSTS_H */
