
#ifndef __INV_COMMENT_H
#define __INV_COMMENT_H

/*
*** this file is automatically generated - DO NOT MODIFY
*/

#include "db.h"

/* Structure definition for the inv_comment table */
struct inv_comment_record {
	long long _id;
	unsigned char _resourceguid[36];
	char comment[1001];
};
#define inv_comment_field_count 3
int inv_comment_fetch(DB *db);
int inv_comment_fetch_record(DB *db, struct inv_comment_record *rec);
int inv_comment_select(DB *db, char *clause);
int inv_comment_select_record(DB *db, struct inv_comment_record *rec, char *clause);
int inv_comment_insert(DB *db, struct inv_comment_record *rec);
int inv_comment_update_record(DB *db, struct inv_comment_record *rec, char *clause);
int inv_comment_delete(DB *db, char *clause);

#endif /* __INV_COMMENT_H */
