
#ifndef __VCOMPUTER_H
#define __VCOMPUTER_H

/*
*** this file is automatically generated - DO NOT MODIFY
*/

#include "db.h"

/* Structure definition for the vcomputer table */
struct vcomputer_record {
	unsigned char guid[36];
	char name[65];
	char domain[65];
	char user[65];
	char os_name[65];
	char os_version[65];
	char ip_address[17];
	char server[251];
	int os_primary_language;
	int os_sub_language;
	char mac_address[25];
	char system_type[65];
	int ismanaged;
	int islocal;
	char createddate[24];
	char os_revision[65];
};
#define vcomputer_field_count 16
int vcomputer_fetch(DB *db);
int vcomputer_fetch_record(DB *db, struct vcomputer_record *rec);
int vcomputer_select(DB *db, char *clause);
int vcomputer_select_record(DB *db, struct vcomputer_record *rec, char *clause);
int vcomputer_insert(DB *db, struct vcomputer_record *rec);
int vcomputer_update_record(DB *db, struct vcomputer_record *rec, char *clause);
int vcomputer_delete(DB *db, char *clause);

#endif /* __VCOMPUTER_H */
