
#ifndef __VRM_ASSET_ITEM_H
#define __VRM_ASSET_ITEM_H

/*
*** this file is automatically generated - DO NOT MODIFY
*/

#include "db.h"

/* Structure definition for the vrm_asset_item table */
struct vrm_asset_item_record {
	unsigned char guid[36];
	unsigned char classguid[36];
	unsigned char resourcetypeguid[36];
	char name[251];
	char description[1001];
	unsigned char ownernsguid[36];
	unsigned char productguid[36];
	unsigned char securityguid[36];
	int attributes;
	char alias[2];
	char createdby[256];
	char modifiedby[256];
	char createddate[24];
	char modifieddate[24];
	int productuninstalled;
	char state[16384];
	int ismanaged;
	int resourceitemdeleted;
};
#define vrm_asset_item_field_count 18
int vrm_asset_item_fetch(DB *db);
int vrm_asset_item_fetch_record(DB *db, struct vrm_asset_item_record *rec);
int vrm_asset_item_select(DB *db, char *clause);
int vrm_asset_item_select_record(DB *db, struct vrm_asset_item_record *rec, char *clause);
int vrm_asset_item_insert(DB *db, struct vrm_asset_item_record *rec);
int vrm_asset_item_update_record(DB *db, struct vrm_asset_item_record *rec, char *clause);
int vrm_asset_item_delete(DB *db, char *clause);

#endif /* __VRM_ASSET_ITEM_H */
