
/*
*** this file is automatically generated - DO NOT MODIFY
*/

#include <stdio.h>
#include <string.h>
#include "gendb__vuson_computertype.h"

int _vuson_computertype_fetch(DB *db) {
#if _vuson_computertype_field_count > 0
	SQLRETURN ret;

	dprintf("Fetching data...\n");
	ret = SQLFetch(db->hstmt);
	if (ret == SQL_SUCCESS || ret == SQL_SUCCESS_WITH_INFO) return 0;
	if (ret != 100) ret = dberr(SQL_HANDLE_STMT,db->hstmt,"_vuson_computertype_fetch");
	return ret;
#else
	return 0;
#endif
}

int _vuson_computertype_fetch_record(DB *db, struct _vuson_computertype_record *rec) {
#if _vuson_computertype_field_count > 0
	SQLRETURN ret;

	if ((ret = _vuson_computertype_fetch(db)) != 0) {
		SQLCloseCursor(db->hstmt);
		return ret;
	}
	memset(rec,0,sizeof(*rec));
	SQLGetData(db->hstmt, 1, SQL_C_BINARY, (SQLPOINTER) rec->guid, sizeof(rec->guid), 0);
	SQLGetData(db->hstmt, 2, SQL_C_CHAR, (SQLPOINTER) rec->name, sizeof(rec->name), 0);
	SQLGetData(db->hstmt, 3, SQL_C_CHAR, (SQLPOINTER) rec->computer_type, sizeof(rec->computer_type), 0);
	SQLGetData(db->hstmt, 4, SQL_C_CHAR, (SQLPOINTER) rec->model, sizeof(rec->model), 0);
	dprintf("----------------- _vuson_computertype record -----------------\n");
	dprintf("guid                :  %x\n",rec->guid);
	dprintf("name                :  %s\n",rec->name);
	dprintf("computer_type       :  %s\n",rec->computer_type);
	dprintf("model               :  %s\n",rec->model);
#endif
	return 0;
}

int _vuson_computertype_select(DB *db, char *clause) {
#if _vuson_computertype_field_count > 0
	char query[4096];
	SQLRETURN ret;

	sprintf(query,"SELECT _vuson_computertype.guid,_vuson_computertype.name,_vuson_computertype.computer_type,_vuson_computertype.model FROM _vuson_computertype %s",(clause ? clause : ""));
	dprintf("Executing query: %s\n", query);
	ret = SQLExecDirect(db->hstmt, (SQLCHAR *) query, SQL_NTS);
	if (ret == SQL_SUCCESS || ret == SQL_SUCCESS_WITH_INFO) return 0;
	ret = dberr(SQL_HANDLE_STMT,db->hstmt,"_vuson_computertype_select");
	return ret;
#else
	return 0;
#endif
}

int _vuson_computertype_select_record(DB *db, struct _vuson_computertype_record *rec, char *clause) {
#if _vuson_computertype_field_count > 0
	SQLRETURN ret;

	if ((ret = _vuson_computertype_select(db, clause)) != 0) return ret;
	if ((ret = _vuson_computertype_fetch_record(db, rec)) != 0) return ret;
	SQLCloseCursor(db->hstmt);
#endif
	return 0;
}

int _vuson_computertype_insert(DB *db, struct _vuson_computertype_record *rec) {
#if _vuson_computertype_field_count > 0
	char query[4096];
	SQLRETURN ret;

	sprintf(query,"INSERT INTO _vuson_computertype (guid,name,computer_type,model) VALUES (%x,'%s','%s','%s')",rec->guid,rec->name,rec->computer_type,rec->model);
	dprintf("Executing query: %s\n", query);
	ret = SQLExecDirect(db->hstmt, (SQLCHAR *) query, SQL_NTS);
	if (ret == SQL_SUCCESS || ret == SQL_SUCCESS_WITH_INFO) return 0;
	ret = dberr(SQL_HANDLE_STMT,db->hstmt,"_vuson_computertype_insert");
	printf("Offending query: %s\n", query);
	return ret;
#else
	return 0;
#endif
}

int _vuson_computertype_update_record(DB *db, struct _vuson_computertype_record *rec, char *clause) {
#if _vuson_computertype_field_count > 0
	char query[4096];
	SQLRETURN ret;

	sprintf(query,"UPDATE _vuson_computertype SET guid = %x,name = '%s',computer_type = '%s',model = '%s'",rec->guid,rec->name,rec->computer_type,rec->model);
	if (clause) {
		if (clause[0] != ' ') strcat(query," ");
		strcat(query,clause);
	}
	dprintf("Executing query: %s\n", query);
	ret = SQLExecDirect(db->hstmt, (SQLCHAR *) query, SQL_NTS);
	if (ret == SQL_SUCCESS || ret == SQL_SUCCESS_WITH_INFO) return 0;
	ret = dberr(SQL_HANDLE_STMT,db->hstmt,"_vuson_computertype_update_record");
	return ret;
#else
	return 0;
#endif
}

int _vuson_computertype_delete(DB *db, char *clause) {
#if _vuson_computertype_field_count > 0
	char query[4096];
	SQLRETURN ret;

	sprintf(query,"DELETE FROM _vuson_computertype %s",(clause ? clause : ""));
	dprintf("Executing query: %s\n", query);
	ret = SQLExecDirect(db->hstmt, (SQLCHAR *) query, SQL_NTS);
	if (ret == SQL_SUCCESS || ret == SQL_SUCCESS_WITH_INFO) return 0;
	ret = dberr(SQL_HANDLE_STMT,db->hstmt,"_vuson_computertype_delete");
	return ret;
#else
	return 0;
#endif
}

