
#ifndef __INV_AEX_AC_IDENTIFICATION_H
#define __INV_AEX_AC_IDENTIFICATION_H

/*
*** this file is automatically generated - DO NOT MODIFY
*/

#include "db.h"

/* Structure definition for the inv_aex_ac_identification table */
struct inv_aex_ac_identification_record {
	long long _id;
	unsigned char _resourceguid[36];
	char guid[41];
	char name[65];
	char domain[65];
	char system_type[65];
	char os_name[65];
	char os_type[65];
	char os_version[65];
	char os_revision[65];
	char last_logon_user[65];
	char last_logon_domain[65];
	char client_date[24];
	int os_major_version;
	int os_minor_version;
	int os_build_number;
	int os_primary_language;
	int os_sub_language;
	int user_primary_language;
	int user_sub_language;
	int install_primary_language;
	int install_sub_language;
	char fqdn[257];
	char unique_id[65];
	int timezone_bias;
	char hardware_serial_number[65];
	char bios_serial_number[65];
	char hw_chassis_serial_number[257];
	long long os_system_mask;
	long long os_comparable_version;
	char os_canonical_name[129];
};
#define inv_aex_ac_identification_field_count 31
int inv_aex_ac_identification_fetch(DB *db);
int inv_aex_ac_identification_fetch_record(DB *db, struct inv_aex_ac_identification_record *rec);
int inv_aex_ac_identification_select(DB *db, char *clause);
int inv_aex_ac_identification_select_record(DB *db, struct inv_aex_ac_identification_record *rec, char *clause);
int inv_aex_ac_identification_insert(DB *db, struct inv_aex_ac_identification_record *rec);
int inv_aex_ac_identification_update_record(DB *db, struct inv_aex_ac_identification_record *rec, char *clause);
int inv_aex_ac_identification_delete(DB *db, char *clause);

#endif /* __INV_AEX_AC_IDENTIFICATION_H */
