
#ifndef __INV_OS_OPERATING_SYSTEM_H
#define __INV_OS_OPERATING_SYSTEM_H

/*
*** this file is automatically generated - DO NOT MODIFY
*/

#include "db.h"

/* Structure definition for the inv_os_operating_system table */
struct inv_os_operating_system_record {
	long long _id;
	unsigned char _resourceguid[36];
	char name[257];
	char install_date[24];
	char last_boot_up_time[24];
	long long max_process_memory_size_(kilobytes);
	int number_of_licensed_users;
	long long total_swap_space_size_(kilobytes);
	char boot_device[257];
	char country_code[7];
	char registered_user[257];
	char serial_number[65];
	int os_architecture;
	long long total_visible_memory_size_(kilobytes);
	int number_of_processors;
};
#define inv_os_operating_system_field_count 15
int inv_os_operating_system_fetch(DB *db);
int inv_os_operating_system_fetch_record(DB *db, struct inv_os_operating_system_record *rec);
int inv_os_operating_system_select(DB *db, char *clause);
int inv_os_operating_system_select_record(DB *db, struct inv_os_operating_system_record *rec, char *clause);
int inv_os_operating_system_insert(DB *db, struct inv_os_operating_system_record *rec);
int inv_os_operating_system_update_record(DB *db, struct inv_os_operating_system_record *rec, char *clause);
int inv_os_operating_system_delete(DB *db, char *clause);

#endif /* __INV_OS_OPERATING_SYSTEM_H */
