
/*
*** this file is automatically generated - DO NOT MODIFY
*/

#include <stdio.h>
#include <string.h>
#include "gendb_inv_aex_ac_identification.h"

int inv_aex_ac_identification_fetch(DB *db) {
#if inv_aex_ac_identification_field_count > 0
	SQLRETURN ret;

	dprintf("Fetching data...\n");
	ret = SQLFetch(db->hstmt);
	if (ret == SQL_SUCCESS || ret == SQL_SUCCESS_WITH_INFO) return 0;
	if (ret != 100) ret = dberr(SQL_HANDLE_STMT,db->hstmt,"inv_aex_ac_identification_fetch");
	return ret;
#else
	return 0;
#endif
}

int inv_aex_ac_identification_fetch_record(DB *db, struct inv_aex_ac_identification_record *rec) {
#if inv_aex_ac_identification_field_count > 0
	SQLRETURN ret;

	if ((ret = inv_aex_ac_identification_fetch(db)) != 0) {
		SQLCloseCursor(db->hstmt);
		return ret;
	}
	memset(rec,0,sizeof(*rec));
	SQLGetData(db->hstmt, 1, SQL_C_BIGINT, (SQLPOINTER) &rec->_id, sizeof(rec->_id), 0);
	SQLGetData(db->hstmt, 2, SQL_C_BINARY, (SQLPOINTER) rec->_resourceguid, sizeof(rec->_resourceguid), 0);
	SQLGetData(db->hstmt, 3, SQL_C_CHAR, (SQLPOINTER) rec->guid, sizeof(rec->guid), 0);
	SQLGetData(db->hstmt, 4, SQL_C_CHAR, (SQLPOINTER) rec->name, sizeof(rec->name), 0);
	SQLGetData(db->hstmt, 5, SQL_C_CHAR, (SQLPOINTER) rec->domain, sizeof(rec->domain), 0);
	SQLGetData(db->hstmt, 6, SQL_C_CHAR, (SQLPOINTER) rec->system_type, sizeof(rec->system_type), 0);
	SQLGetData(db->hstmt, 7, SQL_C_CHAR, (SQLPOINTER) rec->os_name, sizeof(rec->os_name), 0);
	SQLGetData(db->hstmt, 8, SQL_C_CHAR, (SQLPOINTER) rec->os_type, sizeof(rec->os_type), 0);
	SQLGetData(db->hstmt, 9, SQL_C_CHAR, (SQLPOINTER) rec->os_version, sizeof(rec->os_version), 0);
	SQLGetData(db->hstmt, 10, SQL_C_CHAR, (SQLPOINTER) rec->os_revision, sizeof(rec->os_revision), 0);
	SQLGetData(db->hstmt, 11, SQL_C_CHAR, (SQLPOINTER) rec->last_logon_user, sizeof(rec->last_logon_user), 0);
	SQLGetData(db->hstmt, 12, SQL_C_CHAR, (SQLPOINTER) rec->last_logon_domain, sizeof(rec->last_logon_domain), 0);
	SQLGetData(db->hstmt, 13, SQL_C_CHAR, (SQLPOINTER) rec->client_date, sizeof(rec->client_date), 0);
	SQLGetData(db->hstmt, 14, SQL_C_SLONG, (SQLPOINTER) &rec->os_major_version, sizeof(rec->os_major_version), 0);
	SQLGetData(db->hstmt, 15, SQL_C_SLONG, (SQLPOINTER) &rec->os_minor_version, sizeof(rec->os_minor_version), 0);
	SQLGetData(db->hstmt, 16, SQL_C_SLONG, (SQLPOINTER) &rec->os_build_number, sizeof(rec->os_build_number), 0);
	SQLGetData(db->hstmt, 17, SQL_C_SLONG, (SQLPOINTER) &rec->os_primary_language, sizeof(rec->os_primary_language), 0);
	SQLGetData(db->hstmt, 18, SQL_C_SLONG, (SQLPOINTER) &rec->os_sub_language, sizeof(rec->os_sub_language), 0);
	SQLGetData(db->hstmt, 19, SQL_C_SLONG, (SQLPOINTER) &rec->user_primary_language, sizeof(rec->user_primary_language), 0);
	SQLGetData(db->hstmt, 20, SQL_C_SLONG, (SQLPOINTER) &rec->user_sub_language, sizeof(rec->user_sub_language), 0);
	SQLGetData(db->hstmt, 21, SQL_C_SLONG, (SQLPOINTER) &rec->install_primary_language, sizeof(rec->install_primary_language), 0);
	SQLGetData(db->hstmt, 22, SQL_C_SLONG, (SQLPOINTER) &rec->install_sub_language, sizeof(rec->install_sub_language), 0);
	SQLGetData(db->hstmt, 23, SQL_C_CHAR, (SQLPOINTER) rec->fqdn, sizeof(rec->fqdn), 0);
	SQLGetData(db->hstmt, 24, SQL_C_CHAR, (SQLPOINTER) rec->unique_id, sizeof(rec->unique_id), 0);
	SQLGetData(db->hstmt, 25, SQL_C_SLONG, (SQLPOINTER) &rec->timezone_bias, sizeof(rec->timezone_bias), 0);
	SQLGetData(db->hstmt, 26, SQL_C_CHAR, (SQLPOINTER) rec->hardware_serial_number, sizeof(rec->hardware_serial_number), 0);
	SQLGetData(db->hstmt, 27, SQL_C_CHAR, (SQLPOINTER) rec->bios_serial_number, sizeof(rec->bios_serial_number), 0);
	SQLGetData(db->hstmt, 28, SQL_C_CHAR, (SQLPOINTER) rec->hw_chassis_serial_number, sizeof(rec->hw_chassis_serial_number), 0);
	SQLGetData(db->hstmt, 29, SQL_C_BIGINT, (SQLPOINTER) &rec->os_system_mask, sizeof(rec->os_system_mask), 0);
	SQLGetData(db->hstmt, 30, SQL_C_BIGINT, (SQLPOINTER) &rec->os_comparable_version, sizeof(rec->os_comparable_version), 0);
	SQLGetData(db->hstmt, 31, SQL_C_CHAR, (SQLPOINTER) rec->os_canonical_name, sizeof(rec->os_canonical_name), 0);
	dprintf("----------------- inv_aex_ac_identification record -----------------\n");
	dprintf("_id                 :  %lld\n",rec->_id);
	dprintf("_resourceguid       :  %x\n",rec->_resourceguid);
	dprintf("guid                :  %s\n",rec->guid);
	dprintf("name                :  %s\n",rec->name);
	dprintf("domain              :  %s\n",rec->domain);
	dprintf("system_type         :  %s\n",rec->system_type);
	dprintf("os_name             :  %s\n",rec->os_name);
	dprintf("os_type             :  %s\n",rec->os_type);
	dprintf("os_version          :  %s\n",rec->os_version);
	dprintf("os_revision         :  %s\n",rec->os_revision);
	dprintf("last_logon_user     :  %s\n",rec->last_logon_user);
	dprintf("last_logon_domain   :  %s\n",rec->last_logon_domain);
	dprintf("client_date         :  %s\n",rec->client_date);
	dprintf("os_major_version    :  %d\n",rec->os_major_version);
	dprintf("os_minor_version    :  %d\n",rec->os_minor_version);
	dprintf("os_build_number     :  %d\n",rec->os_build_number);
	dprintf("os_primary_language :  %d\n",rec->os_primary_language);
	dprintf("os_sub_language     :  %d\n",rec->os_sub_language);
	dprintf("user_primary_languag:  %d\n",rec->user_primary_language);
	dprintf("user_sub_language   :  %d\n",rec->user_sub_language);
	dprintf("install_primary_lang:  %d\n",rec->install_primary_language);
	dprintf("install_sub_language:  %d\n",rec->install_sub_language);
	dprintf("fqdn                :  %s\n",rec->fqdn);
	dprintf("unique_id           :  %s\n",rec->unique_id);
	dprintf("timezone_bias       :  %d\n",rec->timezone_bias);
	dprintf("hardware_serial_numb:  %s\n",rec->hardware_serial_number);
	dprintf("bios_serial_number  :  %s\n",rec->bios_serial_number);
	dprintf("hw_chassis_serial_nu:  %s\n",rec->hw_chassis_serial_number);
	dprintf("os_system_mask      :  %lld\n",rec->os_system_mask);
	dprintf("os_comparable_versio:  %lld\n",rec->os_comparable_version);
	dprintf("os_canonical_name   :  %s\n",rec->os_canonical_name);
#endif
	return 0;
}

int inv_aex_ac_identification_select(DB *db, char *clause) {
#if inv_aex_ac_identification_field_count > 0
	char query[4096];
	SQLRETURN ret;

	sprintf(query,"SELECT inv_aex_ac_identification._id,inv_aex_ac_identification._resourceguid,inv_aex_ac_identification.guid,inv_aex_ac_identification.name,inv_aex_ac_identification.domain,inv_aex_ac_identification.system_type,inv_aex_ac_identification.os_name,inv_aex_ac_identification.os_type,inv_aex_ac_identification.os_version,inv_aex_ac_identification.os_revision,inv_aex_ac_identification.last_logon_user,inv_aex_ac_identification.last_logon_domain,inv_aex_ac_identification.client_date,inv_aex_ac_identification.os_major_version,inv_aex_ac_identification.os_minor_version,inv_aex_ac_identification.os_build_number,inv_aex_ac_identification.os_primary_language,inv_aex_ac_identification.os_sub_language,inv_aex_ac_identification.user_primary_language,inv_aex_ac_identification.user_sub_language,inv_aex_ac_identification.install_primary_language,inv_aex_ac_identification.install_sub_language,inv_aex_ac_identification.fqdn,inv_aex_ac_identification.unique_id,inv_aex_ac_identification.timezone_bias,inv_aex_ac_identification.hardware_serial_number,inv_aex_ac_identification.bios_serial_number,inv_aex_ac_identification.hw_chassis_serial_number,inv_aex_ac_identification.os_system_mask,inv_aex_ac_identification.os_comparable_version,inv_aex_ac_identification.os_canonical_name FROM inv_aex_ac_identification %s",(clause ? clause : ""));
	dprintf("Executing query: %s\n", query);
	ret = SQLExecDirect(db->hstmt, (SQLCHAR *) query, SQL_NTS);
	if (ret == SQL_SUCCESS || ret == SQL_SUCCESS_WITH_INFO) return 0;
	ret = dberr(SQL_HANDLE_STMT,db->hstmt,"inv_aex_ac_identification_select");
	return ret;
#else
	return 0;
#endif
}

int inv_aex_ac_identification_select_record(DB *db, struct inv_aex_ac_identification_record *rec, char *clause) {
#if inv_aex_ac_identification_field_count > 0
	SQLRETURN ret;

	if ((ret = inv_aex_ac_identification_select(db, clause)) != 0) return ret;
	if ((ret = inv_aex_ac_identification_fetch_record(db, rec)) != 0) return ret;
	SQLCloseCursor(db->hstmt);
#endif
	return 0;
}

int inv_aex_ac_identification_insert(DB *db, struct inv_aex_ac_identification_record *rec) {
#if inv_aex_ac_identification_field_count > 0
	char query[4096];
	SQLRETURN ret;

	sprintf(query,"INSERT INTO inv_aex_ac_identification (_id,_resourceguid,guid,name,domain,system_type,os_name,os_type,os_version,os_revision,last_logon_user,last_logon_domain,client_date,os_major_version,os_minor_version,os_build_number,os_primary_language,os_sub_language,user_primary_language,user_sub_language,install_primary_language,install_sub_language,fqdn,unique_id,timezone_bias,hardware_serial_number,bios_serial_number,hw_chassis_serial_number,os_system_mask,os_comparable_version,os_canonical_name) VALUES (%lld,%x,'%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s',%d,%d,%d,%d,%d,%d,%d,%d,%d,'%s','%s',%d,'%s','%s','%s',%lld,%lld,'%s')",rec->_id,rec->_resourceguid,rec->guid,rec->name,rec->domain,rec->system_type,rec->os_name,rec->os_type,rec->os_version,rec->os_revision,rec->last_logon_user,rec->last_logon_domain,rec->client_date,rec->os_major_version,rec->os_minor_version,rec->os_build_number,rec->os_primary_language,rec->os_sub_language,rec->user_primary_language,rec->user_sub_language,rec->install_primary_language,rec->install_sub_language,rec->fqdn,rec->unique_id,rec->timezone_bias,rec->hardware_serial_number,rec->bios_serial_number,rec->hw_chassis_serial_number,rec->os_system_mask,rec->os_comparable_version,rec->os_canonical_name);
	dprintf("Executing query: %s\n", query);
	ret = SQLExecDirect(db->hstmt, (SQLCHAR *) query, SQL_NTS);
	if (ret == SQL_SUCCESS || ret == SQL_SUCCESS_WITH_INFO) return 0;
	ret = dberr(SQL_HANDLE_STMT,db->hstmt,"inv_aex_ac_identification_insert");
	printf("Offending query: %s\n", query);
	return ret;
#else
	return 0;
#endif
}

int inv_aex_ac_identification_update_record(DB *db, struct inv_aex_ac_identification_record *rec, char *clause) {
#if inv_aex_ac_identification_field_count > 0
	char query[4096];
	SQLRETURN ret;

	sprintf(query,"UPDATE inv_aex_ac_identification SET _id = %lld,_resourceguid = %x,guid = '%s',name = '%s',domain = '%s',system_type = '%s',os_name = '%s',os_type = '%s',os_version = '%s',os_revision = '%s',last_logon_user = '%s',last_logon_domain = '%s',client_date = '%s',os_major_version = %d,os_minor_version = %d,os_build_number = %d,os_primary_language = %d,os_sub_language = %d,user_primary_language = %d,user_sub_language = %d,install_primary_language = %d,install_sub_language = %d,fqdn = '%s',unique_id = '%s',timezone_bias = %d,hardware_serial_number = '%s',bios_serial_number = '%s',hw_chassis_serial_number = '%s',os_system_mask = %lld,os_comparable_version = %lld,os_canonical_name = '%s'",rec->_id,rec->_resourceguid,rec->guid,rec->name,rec->domain,rec->system_type,rec->os_name,rec->os_type,rec->os_version,rec->os_revision,rec->last_logon_user,rec->last_logon_domain,rec->client_date,rec->os_major_version,rec->os_minor_version,rec->os_build_number,rec->os_primary_language,rec->os_sub_language,rec->user_primary_language,rec->user_sub_language,rec->install_primary_language,rec->install_sub_language,rec->fqdn,rec->unique_id,rec->timezone_bias,rec->hardware_serial_number,rec->bios_serial_number,rec->hw_chassis_serial_number,rec->os_system_mask,rec->os_comparable_version,rec->os_canonical_name);
	if (clause) {
		if (clause[0] != ' ') strcat(query," ");
		strcat(query,clause);
	}
	dprintf("Executing query: %s\n", query);
	ret = SQLExecDirect(db->hstmt, (SQLCHAR *) query, SQL_NTS);
	if (ret == SQL_SUCCESS || ret == SQL_SUCCESS_WITH_INFO) return 0;
	ret = dberr(SQL_HANDLE_STMT,db->hstmt,"inv_aex_ac_identification_update_record");
	return ret;
#else
	return 0;
#endif
}

int inv_aex_ac_identification_delete(DB *db, char *clause) {
#if inv_aex_ac_identification_field_count > 0
	char query[4096];
	SQLRETURN ret;

	sprintf(query,"DELETE FROM inv_aex_ac_identification %s",(clause ? clause : ""));
	dprintf("Executing query: %s\n", query);
	ret = SQLExecDirect(db->hstmt, (SQLCHAR *) query, SQL_NTS);
	if (ret == SQL_SUCCESS || ret == SQL_SUCCESS_WITH_INFO) return 0;
	ret = dberr(SQL_HANDLE_STMT,db->hstmt,"inv_aex_ac_identification_delete");
	return ret;
#else
	return 0;
#endif
}

