
/*
*** this file is automatically generated - DO NOT MODIFY
*/

#include <stdio.h>
#include <string.h>
#include "gendb__vuson_concat_asset_svcsys.h"

int _vuson_concat_asset_svcsys_fetch(DB *db) {
#if _vuson_concat_asset_svcsys_field_count > 0
	SQLRETURN ret;

	dprintf("Fetching data...\n");
	ret = SQLFetch(db->hstmt);
	if (ret == SQL_SUCCESS || ret == SQL_SUCCESS_WITH_INFO) return 0;
	if (ret != 100) ret = dberr(SQL_HANDLE_STMT,db->hstmt,"_vuson_concat_asset_svcsys_fetch");
	return ret;
#else
	return 0;
#endif
}

int _vuson_concat_asset_svcsys_fetch_record(DB *db, struct _vuson_concat_asset_svcsys_record *rec) {
#if _vuson_concat_asset_svcsys_field_count > 0
	SQLRETURN ret;

	if ((ret = _vuson_concat_asset_svcsys_fetch(db)) != 0) {
		SQLCloseCursor(db->hstmt);
		return ret;
	}
	memset(rec,0,sizeof(*rec));
	SQLGetData(db->hstmt, 1, SQL_C_BINARY, (SQLPOINTER) rec->assetguid, sizeof(rec->assetguid), 0);
	SQLGetData(db->hstmt, 2, SQL_C_BINARY, (SQLPOINTER) rec->sysguid, sizeof(rec->sysguid), 0);
	SQLGetData(db->hstmt, 3, SQL_C_CHAR, (SQLPOINTER) rec->server_name, sizeof(rec->server_name), 0);
	SQLGetData(db->hstmt, 4, SQL_C_CHAR, (SQLPOINTER) rec->services, sizeof(rec->services), 0);
	SQLGetData(db->hstmt, 5, SQL_C_CHAR, (SQLPOINTER) rec->supporting_systems, sizeof(rec->supporting_systems), 0);
	dprintf("----------------- _vuson_concat_asset_svcsys record -----------------\n");
	dprintf("assetguid           :  %x\n",rec->assetguid);
	dprintf("sysguid             :  %x\n",rec->sysguid);
	dprintf("server_name         :  %s\n",rec->server_name);
	dprintf("services            :  %s\n",rec->services);
	dprintf("supporting_systems  :  %s\n",rec->supporting_systems);
#endif
	return 0;
}

int _vuson_concat_asset_svcsys_select(DB *db, char *clause) {
#if _vuson_concat_asset_svcsys_field_count > 0
	char query[4096];
	SQLRETURN ret;

	sprintf(query,"SELECT _vuson_concat_asset_svcsys.assetguid,_vuson_concat_asset_svcsys.sysguid,_vuson_concat_asset_svcsys.server_name,_vuson_concat_asset_svcsys.services,_vuson_concat_asset_svcsys.supporting_systems FROM _vuson_concat_asset_svcsys %s",(clause ? clause : ""));
	dprintf("Executing query: %s\n", query);
	ret = SQLExecDirect(db->hstmt, (SQLCHAR *) query, SQL_NTS);
	if (ret == SQL_SUCCESS || ret == SQL_SUCCESS_WITH_INFO) return 0;
	ret = dberr(SQL_HANDLE_STMT,db->hstmt,"_vuson_concat_asset_svcsys_select");
	return ret;
#else
	return 0;
#endif
}

int _vuson_concat_asset_svcsys_select_record(DB *db, struct _vuson_concat_asset_svcsys_record *rec, char *clause) {
#if _vuson_concat_asset_svcsys_field_count > 0
	SQLRETURN ret;

	if ((ret = _vuson_concat_asset_svcsys_select(db, clause)) != 0) return ret;
	if ((ret = _vuson_concat_asset_svcsys_fetch_record(db, rec)) != 0) return ret;
	SQLCloseCursor(db->hstmt);
#endif
	return 0;
}

int _vuson_concat_asset_svcsys_insert(DB *db, struct _vuson_concat_asset_svcsys_record *rec) {
#if _vuson_concat_asset_svcsys_field_count > 0
	char query[4096];
	SQLRETURN ret;

	sprintf(query,"INSERT INTO _vuson_concat_asset_svcsys (assetguid,sysguid,server_name,services,supporting_systems) VALUES (%x,%x,'%s','%s','%s')",rec->assetguid,rec->sysguid,rec->server_name,rec->services,rec->supporting_systems);
	dprintf("Executing query: %s\n", query);
	ret = SQLExecDirect(db->hstmt, (SQLCHAR *) query, SQL_NTS);
	if (ret == SQL_SUCCESS || ret == SQL_SUCCESS_WITH_INFO) return 0;
	ret = dberr(SQL_HANDLE_STMT,db->hstmt,"_vuson_concat_asset_svcsys_insert");
	printf("Offending query: %s\n", query);
	return ret;
#else
	return 0;
#endif
}

int _vuson_concat_asset_svcsys_update_record(DB *db, struct _vuson_concat_asset_svcsys_record *rec, char *clause) {
#if _vuson_concat_asset_svcsys_field_count > 0
	char query[4096];
	SQLRETURN ret;

	sprintf(query,"UPDATE _vuson_concat_asset_svcsys SET assetguid = %x,sysguid = %x,server_name = '%s',services = '%s',supporting_systems = '%s'",rec->assetguid,rec->sysguid,rec->server_name,rec->services,rec->supporting_systems);
	if (clause) {
		if (clause[0] != ' ') strcat(query," ");
		strcat(query,clause);
	}
	dprintf("Executing query: %s\n", query);
	ret = SQLExecDirect(db->hstmt, (SQLCHAR *) query, SQL_NTS);
	if (ret == SQL_SUCCESS || ret == SQL_SUCCESS_WITH_INFO) return 0;
	ret = dberr(SQL_HANDLE_STMT,db->hstmt,"_vuson_concat_asset_svcsys_update_record");
	return ret;
#else
	return 0;
#endif
}

int _vuson_concat_asset_svcsys_delete(DB *db, char *clause) {
#if _vuson_concat_asset_svcsys_field_count > 0
	char query[4096];
	SQLRETURN ret;

	sprintf(query,"DELETE FROM _vuson_concat_asset_svcsys %s",(clause ? clause : ""));
	dprintf("Executing query: %s\n", query);
	ret = SQLExecDirect(db->hstmt, (SQLCHAR *) query, SQL_NTS);
	if (ret == SQL_SUCCESS || ret == SQL_SUCCESS_WITH_INFO) return 0;
	ret = dberr(SQL_HANDLE_STMT,db->hstmt,"_vuson_concat_asset_svcsys_delete");
	return ret;
#else
	return 0;
#endif
}

