
#ifndef ___VUSON_COMPUTERTYPE_H
#define ___VUSON_COMPUTERTYPE_H

/*
*** this file is automatically generated - DO NOT MODIFY
*/

#include "db.h"

/* Structure definition for the _vuson_computertype table */
struct _vuson_computertype_record {
	unsigned char guid[36];
	char name[251];
	char computer_type[251];
	char model[101];
};
#define _vuson_computertype_field_count 4
int _vuson_computertype_fetch(DB *db);
int _vuson_computertype_fetch_record(DB *db, struct _vuson_computertype_record *rec);
int _vuson_computertype_select(DB *db, char *clause);
int _vuson_computertype_select_record(DB *db, struct _vuson_computertype_record *rec, char *clause);
int _vuson_computertype_insert(DB *db, struct _vuson_computertype_record *rec);
int _vuson_computertype_update_record(DB *db, struct _vuson_computertype_record *rec, char *clause);
int _vuson_computertype_delete(DB *db, char *clause);

#endif /* ___VUSON_COMPUTERTYPE_H */
