
/*
*** this file is automatically generated - DO NOT MODIFY
*/

#include <stdio.h>
#include <string.h>
#include "gendb_vasset.h"

int vasset_fetch(DB *db) {
#if vasset_field_count > 0
	SQLRETURN ret;

	dprintf("Fetching data...\n");
	ret = SQLFetch(db->hstmt);
	if (ret == SQL_SUCCESS || ret == SQL_SUCCESS_WITH_INFO) return 0;
	if (ret != 100) ret = dberr(SQL_HANDLE_STMT,db->hstmt,"vasset_fetch");
	return ret;
#else
	return 0;
#endif
}

int vasset_fetch_record(DB *db, struct vasset_record *rec) {
#if vasset_field_count > 0
	SQLRETURN ret;

	if ((ret = vasset_fetch(db)) != 0) {
		SQLCloseCursor(db->hstmt);
		return ret;
	}
	memset(rec,0,sizeof(*rec));
	SQLGetData(db->hstmt, 1, SQL_C_BINARY, (SQLPOINTER) rec->_resourceguid, sizeof(rec->_resourceguid), 0);
	SQLGetData(db->hstmt, 2, SQL_C_BINARY, (SQLPOINTER) rec->_resourcetypeguid, sizeof(rec->_resourcetypeguid), 0);
	SQLGetData(db->hstmt, 3, SQL_C_BINARY, (SQLPOINTER) rec->_assetstatusguid, sizeof(rec->_assetstatusguid), 0);
	SQLGetData(db->hstmt, 4, SQL_C_CHAR, (SQLPOINTER) rec->asset_type, sizeof(rec->asset_type), 0);
	SQLGetData(db->hstmt, 5, SQL_C_CHAR, (SQLPOINTER) rec->status, sizeof(rec->status), 0);
	SQLGetData(db->hstmt, 6, SQL_C_CHAR, (SQLPOINTER) rec->manufacturer, sizeof(rec->manufacturer), 0);
	SQLGetData(db->hstmt, 7, SQL_C_CHAR, (SQLPOINTER) rec->model, sizeof(rec->model), 0);
	SQLGetData(db->hstmt, 8, SQL_C_CHAR, (SQLPOINTER) rec->serial_number, sizeof(rec->serial_number), 0);
	SQLGetData(db->hstmt, 9, SQL_C_CHAR, (SQLPOINTER) rec->system_number, sizeof(rec->system_number), 0);
	SQLGetData(db->hstmt, 10, SQL_C_CHAR, (SQLPOINTER) rec->barcode, sizeof(rec->barcode), 0);
	SQLGetData(db->hstmt, 11, SQL_C_CHAR, (SQLPOINTER) rec->last_barcode_scan, sizeof(rec->last_barcode_scan), 0);
	SQLGetData(db->hstmt, 12, SQL_C_CHAR, (SQLPOINTER) rec->asset_tag, sizeof(rec->asset_tag), 0);
	dprintf("----------------- vasset record -----------------\n");
	dprintf("_resourceguid       :  %x\n",rec->_resourceguid);
	dprintf("_resourcetypeguid   :  %x\n",rec->_resourcetypeguid);
	dprintf("_assetstatusguid    :  %x\n",rec->_assetstatusguid);
	dprintf("asset_type          :  %s\n",rec->asset_type);
	dprintf("status              :  %s\n",rec->status);
	dprintf("manufacturer        :  %s\n",rec->manufacturer);
	dprintf("model               :  %s\n",rec->model);
	dprintf("serial_number       :  %s\n",rec->serial_number);
	dprintf("system_number       :  %s\n",rec->system_number);
	dprintf("barcode             :  %s\n",rec->barcode);
	dprintf("last_barcode_scan   :  %s\n",rec->last_barcode_scan);
	dprintf("asset_tag           :  %s\n",rec->asset_tag);
#endif
	return 0;
}

int vasset_select(DB *db, char *clause) {
#if vasset_field_count > 0
	char query[4096];
	SQLRETURN ret;

	sprintf(query,"SELECT vasset._resourceguid,vasset._resourcetypeguid,vasset._assetstatusguid,vasset.asset_type,vasset.status,vasset.manufacturer,vasset.model,vasset.serial_number,vasset.system_number,vasset.barcode,vasset.last_barcode_scan,vasset.asset_tag FROM vasset %s",(clause ? clause : ""));
	dprintf("Executing query: %s\n", query);
	ret = SQLExecDirect(db->hstmt, (SQLCHAR *) query, SQL_NTS);
	if (ret == SQL_SUCCESS || ret == SQL_SUCCESS_WITH_INFO) return 0;
	ret = dberr(SQL_HANDLE_STMT,db->hstmt,"vasset_select");
	return ret;
#else
	return 0;
#endif
}

int vasset_select_record(DB *db, struct vasset_record *rec, char *clause) {
#if vasset_field_count > 0
	SQLRETURN ret;

	if ((ret = vasset_select(db, clause)) != 0) return ret;
	if ((ret = vasset_fetch_record(db, rec)) != 0) return ret;
	SQLCloseCursor(db->hstmt);
#endif
	return 0;
}

int vasset_insert(DB *db, struct vasset_record *rec) {
#if vasset_field_count > 0
	char query[4096];
	SQLRETURN ret;

	sprintf(query,"INSERT INTO vasset (_resourceguid,_resourcetypeguid,_assetstatusguid,asset_type,status,manufacturer,model,serial_number,system_number,barcode,last_barcode_scan,asset_tag) VALUES (%x,%x,%x,'%s','%s','%s','%s','%s','%s','%s','%s','%s')",rec->_resourceguid,rec->_resourcetypeguid,rec->_assetstatusguid,rec->asset_type,rec->status,rec->manufacturer,rec->model,rec->serial_number,rec->system_number,rec->barcode,rec->last_barcode_scan,rec->asset_tag);
	dprintf("Executing query: %s\n", query);
	ret = SQLExecDirect(db->hstmt, (SQLCHAR *) query, SQL_NTS);
	if (ret == SQL_SUCCESS || ret == SQL_SUCCESS_WITH_INFO) return 0;
	ret = dberr(SQL_HANDLE_STMT,db->hstmt,"vasset_insert");
	printf("Offending query: %s\n", query);
	return ret;
#else
	return 0;
#endif
}

int vasset_update_record(DB *db, struct vasset_record *rec, char *clause) {
#if vasset_field_count > 0
	char query[4096];
	SQLRETURN ret;

	sprintf(query,"UPDATE vasset SET _resourceguid = %x,_resourcetypeguid = %x,_assetstatusguid = %x,asset_type = '%s',status = '%s',manufacturer = '%s',model = '%s',serial_number = '%s',system_number = '%s',barcode = '%s',last_barcode_scan = '%s',asset_tag = '%s'",rec->_resourceguid,rec->_resourcetypeguid,rec->_assetstatusguid,rec->asset_type,rec->status,rec->manufacturer,rec->model,rec->serial_number,rec->system_number,rec->barcode,rec->last_barcode_scan,rec->asset_tag);
	if (clause) {
		if (clause[0] != ' ') strcat(query," ");
		strcat(query,clause);
	}
	dprintf("Executing query: %s\n", query);
	ret = SQLExecDirect(db->hstmt, (SQLCHAR *) query, SQL_NTS);
	if (ret == SQL_SUCCESS || ret == SQL_SUCCESS_WITH_INFO) return 0;
	ret = dberr(SQL_HANDLE_STMT,db->hstmt,"vasset_update_record");
	return ret;
#else
	return 0;
#endif
}

int vasset_delete(DB *db, char *clause) {
#if vasset_field_count > 0
	char query[4096];
	SQLRETURN ret;

	sprintf(query,"DELETE FROM vasset %s",(clause ? clause : ""));
	dprintf("Executing query: %s\n", query);
	ret = SQLExecDirect(db->hstmt, (SQLCHAR *) query, SQL_NTS);
	if (ret == SQL_SUCCESS || ret == SQL_SUCCESS_WITH_INFO) return 0;
	ret = dberr(SQL_HANDLE_STMT,db->hstmt,"vasset_delete");
	return ret;
#else
	return 0;
#endif
}

