
/*
*** this file is automatically generated - DO NOT MODIFY
*/

#include <stdio.h>
#include <string.h>
#include "gendb_vcomputer.h"

int vcomputer_fetch(DB *db) {
#if vcomputer_field_count > 0
	SQLRETURN ret;

	dprintf("Fetching data...\n");
	ret = SQLFetch(db->hstmt);
	if (ret == SQL_SUCCESS || ret == SQL_SUCCESS_WITH_INFO) return 0;
	if (ret != 100) ret = dberr(SQL_HANDLE_STMT,db->hstmt,"vcomputer_fetch");
	return ret;
#else
	return 0;
#endif
}

int vcomputer_fetch_record(DB *db, struct vcomputer_record *rec) {
#if vcomputer_field_count > 0
	SQLRETURN ret;

	if ((ret = vcomputer_fetch(db)) != 0) {
		SQLCloseCursor(db->hstmt);
		return ret;
	}
	memset(rec,0,sizeof(*rec));
	SQLGetData(db->hstmt, 1, SQL_C_BINARY, (SQLPOINTER) rec->guid, sizeof(rec->guid), 0);
	SQLGetData(db->hstmt, 2, SQL_C_CHAR, (SQLPOINTER) rec->name, sizeof(rec->name), 0);
	SQLGetData(db->hstmt, 3, SQL_C_CHAR, (SQLPOINTER) rec->domain, sizeof(rec->domain), 0);
	SQLGetData(db->hstmt, 4, SQL_C_CHAR, (SQLPOINTER) rec->user, sizeof(rec->user), 0);
	SQLGetData(db->hstmt, 5, SQL_C_CHAR, (SQLPOINTER) rec->os_name, sizeof(rec->os_name), 0);
	SQLGetData(db->hstmt, 6, SQL_C_CHAR, (SQLPOINTER) rec->os_version, sizeof(rec->os_version), 0);
	SQLGetData(db->hstmt, 7, SQL_C_CHAR, (SQLPOINTER) rec->ip_address, sizeof(rec->ip_address), 0);
	SQLGetData(db->hstmt, 8, SQL_C_CHAR, (SQLPOINTER) rec->server, sizeof(rec->server), 0);
	SQLGetData(db->hstmt, 9, SQL_C_SLONG, (SQLPOINTER) &rec->os_primary_language, sizeof(rec->os_primary_language), 0);
	SQLGetData(db->hstmt, 10, SQL_C_SLONG, (SQLPOINTER) &rec->os_sub_language, sizeof(rec->os_sub_language), 0);
	SQLGetData(db->hstmt, 11, SQL_C_CHAR, (SQLPOINTER) rec->mac_address, sizeof(rec->mac_address), 0);
	SQLGetData(db->hstmt, 12, SQL_C_CHAR, (SQLPOINTER) rec->system_type, sizeof(rec->system_type), 0);
	SQLGetData(db->hstmt, 13, SQL_C_SLONG, (SQLPOINTER) &rec->ismanaged, sizeof(rec->ismanaged), 0);
	SQLGetData(db->hstmt, 14, SQL_C_SLONG, (SQLPOINTER) &rec->islocal, sizeof(rec->islocal), 0);
	SQLGetData(db->hstmt, 15, SQL_C_CHAR, (SQLPOINTER) rec->createddate, sizeof(rec->createddate), 0);
	SQLGetData(db->hstmt, 16, SQL_C_CHAR, (SQLPOINTER) rec->os_revision, sizeof(rec->os_revision), 0);
	dprintf("----------------- vcomputer record -----------------\n");
	dprintf("guid                :  %x\n",rec->guid);
	dprintf("name                :  %s\n",rec->name);
	dprintf("domain              :  %s\n",rec->domain);
	dprintf("user                :  %s\n",rec->user);
	dprintf("os_name             :  %s\n",rec->os_name);
	dprintf("os_version          :  %s\n",rec->os_version);
	dprintf("ip_address          :  %s\n",rec->ip_address);
	dprintf("server              :  %s\n",rec->server);
	dprintf("os_primary_language :  %d\n",rec->os_primary_language);
	dprintf("os_sub_language     :  %d\n",rec->os_sub_language);
	dprintf("mac_address         :  %s\n",rec->mac_address);
	dprintf("system_type         :  %s\n",rec->system_type);
	dprintf("ismanaged           :  %d\n",rec->ismanaged);
	dprintf("islocal             :  %d\n",rec->islocal);
	dprintf("createddate         :  %s\n",rec->createddate);
	dprintf("os_revision         :  %s\n",rec->os_revision);
#endif
	return 0;
}

int vcomputer_select(DB *db, char *clause) {
#if vcomputer_field_count > 0
	char query[4096];
	SQLRETURN ret;

	sprintf(query,"SELECT vcomputer.guid,vcomputer.name,vcomputer.domain,vcomputer.user,vcomputer.os_name,vcomputer.os_version,vcomputer.ip_address,vcomputer.server,vcomputer.os_primary_language,vcomputer.os_sub_language,vcomputer.mac_address,vcomputer.system_type,vcomputer.ismanaged,vcomputer.islocal,vcomputer.createddate,vcomputer.os_revision FROM vcomputer %s",(clause ? clause : ""));
	dprintf("Executing query: %s\n", query);
	ret = SQLExecDirect(db->hstmt, (SQLCHAR *) query, SQL_NTS);
	if (ret == SQL_SUCCESS || ret == SQL_SUCCESS_WITH_INFO) return 0;
	ret = dberr(SQL_HANDLE_STMT,db->hstmt,"vcomputer_select");
	return ret;
#else
	return 0;
#endif
}

int vcomputer_select_record(DB *db, struct vcomputer_record *rec, char *clause) {
#if vcomputer_field_count > 0
	SQLRETURN ret;

	if ((ret = vcomputer_select(db, clause)) != 0) return ret;
	if ((ret = vcomputer_fetch_record(db, rec)) != 0) return ret;
	SQLCloseCursor(db->hstmt);
#endif
	return 0;
}

int vcomputer_insert(DB *db, struct vcomputer_record *rec) {
#if vcomputer_field_count > 0
	char query[4096];
	SQLRETURN ret;

	sprintf(query,"INSERT INTO vcomputer (guid,name,domain,user,os_name,os_version,ip_address,server,os_primary_language,os_sub_language,mac_address,system_type,ismanaged,islocal,createddate,os_revision) VALUES (%x,'%s','%s','%s','%s','%s','%s','%s',%d,%d,'%s','%s',%d,%d,'%s','%s')",rec->guid,rec->name,rec->domain,rec->user,rec->os_name,rec->os_version,rec->ip_address,rec->server,rec->os_primary_language,rec->os_sub_language,rec->mac_address,rec->system_type,rec->ismanaged,rec->islocal,rec->createddate,rec->os_revision);
	dprintf("Executing query: %s\n", query);
	ret = SQLExecDirect(db->hstmt, (SQLCHAR *) query, SQL_NTS);
	if (ret == SQL_SUCCESS || ret == SQL_SUCCESS_WITH_INFO) return 0;
	ret = dberr(SQL_HANDLE_STMT,db->hstmt,"vcomputer_insert");
	printf("Offending query: %s\n", query);
	return ret;
#else
	return 0;
#endif
}

int vcomputer_update_record(DB *db, struct vcomputer_record *rec, char *clause) {
#if vcomputer_field_count > 0
	char query[4096];
	SQLRETURN ret;

	sprintf(query,"UPDATE vcomputer SET guid = %x,name = '%s',domain = '%s',user = '%s',os_name = '%s',os_version = '%s',ip_address = '%s',server = '%s',os_primary_language = %d,os_sub_language = %d,mac_address = '%s',system_type = '%s',ismanaged = %d,islocal = %d,createddate = '%s',os_revision = '%s'",rec->guid,rec->name,rec->domain,rec->user,rec->os_name,rec->os_version,rec->ip_address,rec->server,rec->os_primary_language,rec->os_sub_language,rec->mac_address,rec->system_type,rec->ismanaged,rec->islocal,rec->createddate,rec->os_revision);
	if (clause) {
		if (clause[0] != ' ') strcat(query," ");
		strcat(query,clause);
	}
	dprintf("Executing query: %s\n", query);
	ret = SQLExecDirect(db->hstmt, (SQLCHAR *) query, SQL_NTS);
	if (ret == SQL_SUCCESS || ret == SQL_SUCCESS_WITH_INFO) return 0;
	ret = dberr(SQL_HANDLE_STMT,db->hstmt,"vcomputer_update_record");
	return ret;
#else
	return 0;
#endif
}

int vcomputer_delete(DB *db, char *clause) {
#if vcomputer_field_count > 0
	char query[4096];
	SQLRETURN ret;

	sprintf(query,"DELETE FROM vcomputer %s",(clause ? clause : ""));
	dprintf("Executing query: %s\n", query);
	ret = SQLExecDirect(db->hstmt, (SQLCHAR *) query, SQL_NTS);
	if (ret == SQL_SUCCESS || ret == SQL_SUCCESS_WITH_INFO) return 0;
	ret = dberr(SQL_HANDLE_STMT,db->hstmt,"vcomputer_delete");
	return ret;
#else
	return 0;
#endif
}

