
/*
*** this file is automatically generated - DO NOT MODIFY
*/

#include <stdio.h>
#include <string.h>
#include "gendb_inv_uson_backup_info.h"

int inv_uson_backup_info_fetch(DB *db) {
#if inv_uson_backup_info_field_count > 0
	SQLRETURN ret;

	dprintf("Fetching data...\n");
	ret = SQLFetch(db->hstmt);
	if (ret == SQL_SUCCESS || ret == SQL_SUCCESS_WITH_INFO) return 0;
	if (ret != 100) ret = dberr(SQL_HANDLE_STMT,db->hstmt,"inv_uson_backup_info_fetch");
	return ret;
#else
	return 0;
#endif
}

int inv_uson_backup_info_fetch_record(DB *db, struct inv_uson_backup_info_record *rec) {
#if inv_uson_backup_info_field_count > 0
	SQLRETURN ret;

	if ((ret = inv_uson_backup_info_fetch(db)) != 0) {
		SQLCloseCursor(db->hstmt);
		return ret;
	}
	memset(rec,0,sizeof(*rec));
	SQLGetData(db->hstmt, 1, SQL_C_BIGINT, (SQLPOINTER) &rec->_id, sizeof(rec->_id), 0);
	SQLGetData(db->hstmt, 2, SQL_C_BINARY, (SQLPOINTER) rec->_resourceguid, sizeof(rec->_resourceguid), 0);
	SQLGetData(db->hstmt, 3, SQL_C_CHAR, (SQLPOINTER) rec->backup_method, sizeof(rec->backup_method), 0);
	SQLGetData(db->hstmt, 4, SQL_C_CHAR, (SQLPOINTER) rec->backup_ip, sizeof(rec->backup_ip), 0);
	SQLGetData(db->hstmt, 5, SQL_C_CHAR, (SQLPOINTER) rec->detail_-_backup_method, sizeof(rec->detail_-_backup_method), 0);
	dprintf("----------------- inv_uson_backup_info record -----------------\n");
	dprintf("_id                 :  %lld\n",rec->_id);
	dprintf("_resourceguid       :  %x\n",rec->_resourceguid);
	dprintf("backup_method       :  %s\n",rec->backup_method);
	dprintf("backup_ip           :  %s\n",rec->backup_ip);
	dprintf("detail_-_backup_meth:  %s\n",rec->detail_-_backup_method);
#endif
	return 0;
}

int inv_uson_backup_info_select(DB *db, char *clause) {
#if inv_uson_backup_info_field_count > 0
	char query[4096];
	SQLRETURN ret;

	sprintf(query,"SELECT inv_uson_backup_info._id,inv_uson_backup_info._resourceguid,inv_uson_backup_info.backup_method,inv_uson_backup_info.backup_ip,inv_uson_backup_info.detail_-_backup_method FROM inv_uson_backup_info %s",(clause ? clause : ""));
	dprintf("Executing query: %s\n", query);
	ret = SQLExecDirect(db->hstmt, (SQLCHAR *) query, SQL_NTS);
	if (ret == SQL_SUCCESS || ret == SQL_SUCCESS_WITH_INFO) return 0;
	ret = dberr(SQL_HANDLE_STMT,db->hstmt,"inv_uson_backup_info_select");
	return ret;
#else
	return 0;
#endif
}

int inv_uson_backup_info_select_record(DB *db, struct inv_uson_backup_info_record *rec, char *clause) {
#if inv_uson_backup_info_field_count > 0
	SQLRETURN ret;

	if ((ret = inv_uson_backup_info_select(db, clause)) != 0) return ret;
	if ((ret = inv_uson_backup_info_fetch_record(db, rec)) != 0) return ret;
	SQLCloseCursor(db->hstmt);
#endif
	return 0;
}

int inv_uson_backup_info_insert(DB *db, struct inv_uson_backup_info_record *rec) {
#if inv_uson_backup_info_field_count > 0
	char query[4096];
	SQLRETURN ret;

	sprintf(query,"INSERT INTO inv_uson_backup_info (_id,_resourceguid,backup_method,backup_ip,detail_-_backup_method) VALUES (%lld,%x,'%s','%s','%s')",rec->_id,rec->_resourceguid,rec->backup_method,rec->backup_ip,rec->detail_-_backup_method);
	dprintf("Executing query: %s\n", query);
	ret = SQLExecDirect(db->hstmt, (SQLCHAR *) query, SQL_NTS);
	if (ret == SQL_SUCCESS || ret == SQL_SUCCESS_WITH_INFO) return 0;
	ret = dberr(SQL_HANDLE_STMT,db->hstmt,"inv_uson_backup_info_insert");
	printf("Offending query: %s\n", query);
	return ret;
#else
	return 0;
#endif
}

int inv_uson_backup_info_update_record(DB *db, struct inv_uson_backup_info_record *rec, char *clause) {
#if inv_uson_backup_info_field_count > 0
	char query[4096];
	SQLRETURN ret;

	sprintf(query,"UPDATE inv_uson_backup_info SET _id = %lld,_resourceguid = %x,backup_method = '%s',backup_ip = '%s',detail_-_backup_method = '%s'",rec->_id,rec->_resourceguid,rec->backup_method,rec->backup_ip,rec->detail_-_backup_method);
	if (clause) {
		if (clause[0] != ' ') strcat(query," ");
		strcat(query,clause);
	}
	dprintf("Executing query: %s\n", query);
	ret = SQLExecDirect(db->hstmt, (SQLCHAR *) query, SQL_NTS);
	if (ret == SQL_SUCCESS || ret == SQL_SUCCESS_WITH_INFO) return 0;
	ret = dberr(SQL_HANDLE_STMT,db->hstmt,"inv_uson_backup_info_update_record");
	return ret;
#else
	return 0;
#endif
}

int inv_uson_backup_info_delete(DB *db, char *clause) {
#if inv_uson_backup_info_field_count > 0
	char query[4096];
	SQLRETURN ret;

	sprintf(query,"DELETE FROM inv_uson_backup_info %s",(clause ? clause : ""));
	dprintf("Executing query: %s\n", query);
	ret = SQLExecDirect(db->hstmt, (SQLCHAR *) query, SQL_NTS);
	if (ret == SQL_SUCCESS || ret == SQL_SUCCESS_WITH_INFO) return 0;
	ret = dberr(SQL_HANDLE_STMT,db->hstmt,"inv_uson_backup_info_delete");
	return ret;
#else
	return 0;
#endif
}

