
/*
*** this file is automatically generated - DO NOT MODIFY
*/

#include <stdio.h>
#include <string.h>
#include "gendb_inv_uson_system_support.h"

int inv_uson_system_support_fetch(DB *db) {
#if inv_uson_system_support_field_count > 0
	SQLRETURN ret;

	dprintf("Fetching data...\n");
	ret = SQLFetch(db->hstmt);
	if (ret == SQL_SUCCESS || ret == SQL_SUCCESS_WITH_INFO) return 0;
	if (ret != 100) ret = dberr(SQL_HANDLE_STMT,db->hstmt,"inv_uson_system_support_fetch");
	return ret;
#else
	return 0;
#endif
}

int inv_uson_system_support_fetch_record(DB *db, struct inv_uson_system_support_record *rec) {
#if inv_uson_system_support_field_count > 0
	SQLRETURN ret;

	if ((ret = inv_uson_system_support_fetch(db)) != 0) {
		SQLCloseCursor(db->hstmt);
		return ret;
	}
	memset(rec,0,sizeof(*rec));
	SQLGetData(db->hstmt, 1, SQL_C_BIGINT, (SQLPOINTER) &rec->_id, sizeof(rec->_id), 0);
	SQLGetData(db->hstmt, 2, SQL_C_BINARY, (SQLPOINTER) rec->_resourceguid, sizeof(rec->_resourceguid), 0);
	SQLGetData(db->hstmt, 3, SQL_C_CHAR, (SQLPOINTER) rec->tech_support, sizeof(rec->tech_support), 0);
	SQLGetData(db->hstmt, 4, SQL_C_CHAR, (SQLPOINTER) rec->app_support, sizeof(rec->app_support), 0);
	dprintf("----------------- inv_uson_system_support record -----------------\n");
	dprintf("_id                 :  %lld\n",rec->_id);
	dprintf("_resourceguid       :  %x\n",rec->_resourceguid);
	dprintf("tech_support        :  %s\n",rec->tech_support);
	dprintf("app_support         :  %s\n",rec->app_support);
#endif
	return 0;
}

int inv_uson_system_support_select(DB *db, char *clause) {
#if inv_uson_system_support_field_count > 0
	char query[4096];
	SQLRETURN ret;

	sprintf(query,"SELECT inv_uson_system_support._id,inv_uson_system_support._resourceguid,inv_uson_system_support.tech_support,inv_uson_system_support.app_support FROM inv_uson_system_support %s",(clause ? clause : ""));
	dprintf("Executing query: %s\n", query);
	ret = SQLExecDirect(db->hstmt, (SQLCHAR *) query, SQL_NTS);
	if (ret == SQL_SUCCESS || ret == SQL_SUCCESS_WITH_INFO) return 0;
	ret = dberr(SQL_HANDLE_STMT,db->hstmt,"inv_uson_system_support_select");
	return ret;
#else
	return 0;
#endif
}

int inv_uson_system_support_select_record(DB *db, struct inv_uson_system_support_record *rec, char *clause) {
#if inv_uson_system_support_field_count > 0
	SQLRETURN ret;

	if ((ret = inv_uson_system_support_select(db, clause)) != 0) return ret;
	if ((ret = inv_uson_system_support_fetch_record(db, rec)) != 0) return ret;
	SQLCloseCursor(db->hstmt);
#endif
	return 0;
}

int inv_uson_system_support_insert(DB *db, struct inv_uson_system_support_record *rec) {
#if inv_uson_system_support_field_count > 0
	char query[4096];
	SQLRETURN ret;

	sprintf(query,"INSERT INTO inv_uson_system_support (_id,_resourceguid,tech_support,app_support) VALUES (%lld,%x,'%s','%s')",rec->_id,rec->_resourceguid,rec->tech_support,rec->app_support);
	dprintf("Executing query: %s\n", query);
	ret = SQLExecDirect(db->hstmt, (SQLCHAR *) query, SQL_NTS);
	if (ret == SQL_SUCCESS || ret == SQL_SUCCESS_WITH_INFO) return 0;
	ret = dberr(SQL_HANDLE_STMT,db->hstmt,"inv_uson_system_support_insert");
	printf("Offending query: %s\n", query);
	return ret;
#else
	return 0;
#endif
}

int inv_uson_system_support_update_record(DB *db, struct inv_uson_system_support_record *rec, char *clause) {
#if inv_uson_system_support_field_count > 0
	char query[4096];
	SQLRETURN ret;

	sprintf(query,"UPDATE inv_uson_system_support SET _id = %lld,_resourceguid = %x,tech_support = '%s',app_support = '%s'",rec->_id,rec->_resourceguid,rec->tech_support,rec->app_support);
	if (clause) {
		if (clause[0] != ' ') strcat(query," ");
		strcat(query,clause);
	}
	dprintf("Executing query: %s\n", query);
	ret = SQLExecDirect(db->hstmt, (SQLCHAR *) query, SQL_NTS);
	if (ret == SQL_SUCCESS || ret == SQL_SUCCESS_WITH_INFO) return 0;
	ret = dberr(SQL_HANDLE_STMT,db->hstmt,"inv_uson_system_support_update_record");
	return ret;
#else
	return 0;
#endif
}

int inv_uson_system_support_delete(DB *db, char *clause) {
#if inv_uson_system_support_field_count > 0
	char query[4096];
	SQLRETURN ret;

	sprintf(query,"DELETE FROM inv_uson_system_support %s",(clause ? clause : ""));
	dprintf("Executing query: %s\n", query);
	ret = SQLExecDirect(db->hstmt, (SQLCHAR *) query, SQL_NTS);
	if (ret == SQL_SUCCESS || ret == SQL_SUCCESS_WITH_INFO) return 0;
	ret = dberr(SQL_HANDLE_STMT,db->hstmt,"inv_uson_system_support_delete");
	return ret;
#else
	return 0;
#endif
}

