
/*
*** this file is automatically generated - DO NOT MODIFY
*/

#include <stdio.h>
#include <string.h>
#include "gendb_inv_os_operating_system.h"

int inv_os_operating_system_fetch(DB *db) {
#if inv_os_operating_system_field_count > 0
	SQLRETURN ret;

	dprintf("Fetching data...\n");
	ret = SQLFetch(db->hstmt);
	if (ret == SQL_SUCCESS || ret == SQL_SUCCESS_WITH_INFO) return 0;
	if (ret != 100) ret = dberr(SQL_HANDLE_STMT,db->hstmt,"inv_os_operating_system_fetch");
	return ret;
#else
	return 0;
#endif
}

int inv_os_operating_system_fetch_record(DB *db, struct inv_os_operating_system_record *rec) {
#if inv_os_operating_system_field_count > 0
	SQLRETURN ret;

	if ((ret = inv_os_operating_system_fetch(db)) != 0) {
		SQLCloseCursor(db->hstmt);
		return ret;
	}
	memset(rec,0,sizeof(*rec));
	SQLGetData(db->hstmt, 1, SQL_C_BIGINT, (SQLPOINTER) &rec->_id, sizeof(rec->_id), 0);
	SQLGetData(db->hstmt, 2, SQL_C_BINARY, (SQLPOINTER) rec->_resourceguid, sizeof(rec->_resourceguid), 0);
	SQLGetData(db->hstmt, 3, SQL_C_CHAR, (SQLPOINTER) rec->name, sizeof(rec->name), 0);
	SQLGetData(db->hstmt, 4, SQL_C_CHAR, (SQLPOINTER) rec->install_date, sizeof(rec->install_date), 0);
	SQLGetData(db->hstmt, 5, SQL_C_CHAR, (SQLPOINTER) rec->last_boot_up_time, sizeof(rec->last_boot_up_time), 0);
	SQLGetData(db->hstmt, 6, SQL_C_BIGINT, (SQLPOINTER) &rec->max_process_memory_size_(kilobytes), sizeof(rec->max_process_memory_size_(kilobytes)), 0);
	SQLGetData(db->hstmt, 7, SQL_C_SLONG, (SQLPOINTER) &rec->number_of_licensed_users, sizeof(rec->number_of_licensed_users), 0);
	SQLGetData(db->hstmt, 8, SQL_C_BIGINT, (SQLPOINTER) &rec->total_swap_space_size_(kilobytes), sizeof(rec->total_swap_space_size_(kilobytes)), 0);
	SQLGetData(db->hstmt, 9, SQL_C_CHAR, (SQLPOINTER) rec->boot_device, sizeof(rec->boot_device), 0);
	SQLGetData(db->hstmt, 10, SQL_C_CHAR, (SQLPOINTER) rec->country_code, sizeof(rec->country_code), 0);
	SQLGetData(db->hstmt, 11, SQL_C_CHAR, (SQLPOINTER) rec->registered_user, sizeof(rec->registered_user), 0);
	SQLGetData(db->hstmt, 12, SQL_C_CHAR, (SQLPOINTER) rec->serial_number, sizeof(rec->serial_number), 0);
	SQLGetData(db->hstmt, 13, SQL_C_SLONG, (SQLPOINTER) &rec->os_architecture, sizeof(rec->os_architecture), 0);
	SQLGetData(db->hstmt, 14, SQL_C_BIGINT, (SQLPOINTER) &rec->total_visible_memory_size_(kilobytes), sizeof(rec->total_visible_memory_size_(kilobytes)), 0);
	SQLGetData(db->hstmt, 15, SQL_C_SLONG, (SQLPOINTER) &rec->number_of_processors, sizeof(rec->number_of_processors), 0);
	dprintf("----------------- inv_os_operating_system record -----------------\n");
	dprintf("_id                 :  %lld\n",rec->_id);
	dprintf("_resourceguid       :  %x\n",rec->_resourceguid);
	dprintf("name                :  %s\n",rec->name);
	dprintf("install_date        :  %s\n",rec->install_date);
	dprintf("last_boot_up_time   :  %s\n",rec->last_boot_up_time);
	dprintf("max_process_memory_s:  %lld\n",rec->max_process_memory_size_(kilobytes));
	dprintf("number_of_licensed_u:  %d\n",rec->number_of_licensed_users);
	dprintf("total_swap_space_siz:  %lld\n",rec->total_swap_space_size_(kilobytes));
	dprintf("boot_device         :  %s\n",rec->boot_device);
	dprintf("country_code        :  %s\n",rec->country_code);
	dprintf("registered_user     :  %s\n",rec->registered_user);
	dprintf("serial_number       :  %s\n",rec->serial_number);
	dprintf("os_architecture     :  %d\n",rec->os_architecture);
	dprintf("total_visible_memory:  %lld\n",rec->total_visible_memory_size_(kilobytes));
	dprintf("number_of_processors:  %d\n",rec->number_of_processors);
#endif
	return 0;
}

int inv_os_operating_system_select(DB *db, char *clause) {
#if inv_os_operating_system_field_count > 0
	char query[4096];
	SQLRETURN ret;

	sprintf(query,"SELECT inv_os_operating_system._id,inv_os_operating_system._resourceguid,inv_os_operating_system.name,inv_os_operating_system.install_date,inv_os_operating_system.last_boot_up_time,inv_os_operating_system.max_process_memory_size_(kilobytes),inv_os_operating_system.number_of_licensed_users,inv_os_operating_system.total_swap_space_size_(kilobytes),inv_os_operating_system.boot_device,inv_os_operating_system.country_code,inv_os_operating_system.registered_user,inv_os_operating_system.serial_number,inv_os_operating_system.os_architecture,inv_os_operating_system.total_visible_memory_size_(kilobytes),inv_os_operating_system.number_of_processors FROM inv_os_operating_system %s",(clause ? clause : ""));
	dprintf("Executing query: %s\n", query);
	ret = SQLExecDirect(db->hstmt, (SQLCHAR *) query, SQL_NTS);
	if (ret == SQL_SUCCESS || ret == SQL_SUCCESS_WITH_INFO) return 0;
	ret = dberr(SQL_HANDLE_STMT,db->hstmt,"inv_os_operating_system_select");
	return ret;
#else
	return 0;
#endif
}

int inv_os_operating_system_select_record(DB *db, struct inv_os_operating_system_record *rec, char *clause) {
#if inv_os_operating_system_field_count > 0
	SQLRETURN ret;

	if ((ret = inv_os_operating_system_select(db, clause)) != 0) return ret;
	if ((ret = inv_os_operating_system_fetch_record(db, rec)) != 0) return ret;
	SQLCloseCursor(db->hstmt);
#endif
	return 0;
}

int inv_os_operating_system_insert(DB *db, struct inv_os_operating_system_record *rec) {
#if inv_os_operating_system_field_count > 0
	char query[4096];
	SQLRETURN ret;

	sprintf(query,"INSERT INTO inv_os_operating_system (_id,_resourceguid,name,install_date,last_boot_up_time,max_process_memory_size_(kilobytes),number_of_licensed_users,total_swap_space_size_(kilobytes),boot_device,country_code,registered_user,serial_number,os_architecture,total_visible_memory_size_(kilobytes),number_of_processors) VALUES (%lld,%x,'%s','%s','%s',%lld,%d,%lld,'%s','%s','%s','%s',%d,%lld,%d)",rec->_id,rec->_resourceguid,rec->name,rec->install_date,rec->last_boot_up_time,rec->max_process_memory_size_(kilobytes),rec->number_of_licensed_users,rec->total_swap_space_size_(kilobytes),rec->boot_device,rec->country_code,rec->registered_user,rec->serial_number,rec->os_architecture,rec->total_visible_memory_size_(kilobytes),rec->number_of_processors);
	dprintf("Executing query: %s\n", query);
	ret = SQLExecDirect(db->hstmt, (SQLCHAR *) query, SQL_NTS);
	if (ret == SQL_SUCCESS || ret == SQL_SUCCESS_WITH_INFO) return 0;
	ret = dberr(SQL_HANDLE_STMT,db->hstmt,"inv_os_operating_system_insert");
	printf("Offending query: %s\n", query);
	return ret;
#else
	return 0;
#endif
}

int inv_os_operating_system_update_record(DB *db, struct inv_os_operating_system_record *rec, char *clause) {
#if inv_os_operating_system_field_count > 0
	char query[4096];
	SQLRETURN ret;

	sprintf(query,"UPDATE inv_os_operating_system SET _id = %lld,_resourceguid = %x,name = '%s',install_date = '%s',last_boot_up_time = '%s',max_process_memory_size_(kilobytes) = %lld,number_of_licensed_users = %d,total_swap_space_size_(kilobytes) = %lld,boot_device = '%s',country_code = '%s',registered_user = '%s',serial_number = '%s',os_architecture = %d,total_visible_memory_size_(kilobytes) = %lld,number_of_processors = %d",rec->_id,rec->_resourceguid,rec->name,rec->install_date,rec->last_boot_up_time,rec->max_process_memory_size_(kilobytes),rec->number_of_licensed_users,rec->total_swap_space_size_(kilobytes),rec->boot_device,rec->country_code,rec->registered_user,rec->serial_number,rec->os_architecture,rec->total_visible_memory_size_(kilobytes),rec->number_of_processors);
	if (clause) {
		if (clause[0] != ' ') strcat(query," ");
		strcat(query,clause);
	}
	dprintf("Executing query: %s\n", query);
	ret = SQLExecDirect(db->hstmt, (SQLCHAR *) query, SQL_NTS);
	if (ret == SQL_SUCCESS || ret == SQL_SUCCESS_WITH_INFO) return 0;
	ret = dberr(SQL_HANDLE_STMT,db->hstmt,"inv_os_operating_system_update_record");
	return ret;
#else
	return 0;
#endif
}

int inv_os_operating_system_delete(DB *db, char *clause) {
#if inv_os_operating_system_field_count > 0
	char query[4096];
	SQLRETURN ret;

	sprintf(query,"DELETE FROM inv_os_operating_system %s",(clause ? clause : ""));
	dprintf("Executing query: %s\n", query);
	ret = SQLExecDirect(db->hstmt, (SQLCHAR *) query, SQL_NTS);
	if (ret == SQL_SUCCESS || ret == SQL_SUCCESS_WITH_INFO) return 0;
	ret = dberr(SQL_HANDLE_STMT,db->hstmt,"inv_os_operating_system_delete");
	return ret;
#else
	return 0;
#endif
}

