#!/bin/bash
test -z "$1" && exit 1
if test `echo $1 | awk '{ print substr($0,3,1) }'` = "u"; then
	KEY=""
	USER=""
	ROOT="/opt/pb/bin/pbrun ksh -c"
else
	KEY="-i $HOME/etc/sysadm"
	USER="sysadm@"
	ROOT="sudo su root -c"
fi
ssh -n -q -o BatchMode=yes $KEY "$USER"$1 "$ROOT \"rm -f /tmp/xplist\""
scp -B -o ConnectTimeout=10 $KEY xplist "$USER"$1:/tmp > /dev/null 2>&1
test $? -ne 0 && exit 1
ssh -n -q -o BatchMode=yes $KEY "$USER"$1 "$ROOT \"chmod 755 /tmp/xplist; /tmp/xplist -V; rm -f /tmp/xplist\""
