#!/bin/bash

. /usr/local/etc/.builder

tmplog=/tmp/ilocmd.$$
trap '{ rm -f $tmplog; }' EXIT
logfile=/dev/null

tools=/usr/local/lib/tools
lib=/usr/local/lib/builder
if test `echo $0 | grep -c '^\./'` -eq 1; then
        tools="."
        lib="."
fi

ilocmd() {
	$tools/locfg.pl -s $ilo -u $ilo_user -p $ilo_pass -f $2 > $tmplog
	if test `cat $tmplog | grep "MESSAGE=" | grep -c -v 'No error'` -gt 0; then
		test -n "$logfile" && cat $tmplog >> $logfile
		if test $1 -eq 1; then
			echo "ERROR: message from ilo"
			cat $tmplog
			exit 1
		fi
	fi
}

waitpower() {
	$tools/locfg.pl -s $ilo -u $ilo_user -p $ilo_pass -f $lib/powerstate.xml > $tmplog
	retry=15
	while test `cat $tmplog | grep HOST_POWER= | awk -F= '{ print $2 }' | grep -c ON` -ne $1
	do
		sleep 2
		$tools/locfg.pl -s $ilo -u $ilo_user -p $ilo_pass -f $lib/powerstate.xml > $tmplog
		let retry=$retry-1
		test $retry -eq 0 && return 1
	done
	cat $tmplog >> $logfile
	return 0
}

op="$1"; shift
case $op in
on)
	cmd=$lib/poweron.xml
	wait="1"
	;;
off)
	cmd=$lib/poweroff.xml
	wait="0"
	;;
*)
	echo "unknown op: $op"
	exit 1
esac

if test `echo $1 | grep -c -E '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$'` -eq 0; then
	ilo=`getcons $1`
else
	ilo=$1
fi
echo $ilo
exit 0
test -z "$ilo" && ilo=unknown
test "$ilo" = "unknown" && exit 1
ilocmd 1 $cmd
test -n $wait && waitpower $wait
