
#include "gendb.h"

#if 0
int write_pc_file(table_name,prefix,field_list)
char *table_name,*prefix;
TABLE_INFO *field_list;
{
	FILE *fp;
	char filename[40],line[80];
	TABLE_INFO *cur_field;
	KEY_INFO *cur_key;
	int has_string;

	if (opts & OPT_DEBUG) printf("write_pc: opening file: %s.pc\n",prefix);
	sprintf(filename,"%s.pc",prefix);
	fp = fopen(filename,"w+");
	if (!fp) {
		perror("unable to open pc file");
		return 1;
	}

	/* Write a comment */
	fprintf(fp,"\n");
	fprintf(fp,"/*\n");
	fprintf(fp,"*** %s pc file generated by genpc\n",table_name);
	fprintf(fp,"*/\n");
	if (opts & OPT_DEBUG) printf("write_pc: writing funcs:");

	/* Write the open function */
	if (opts & OPT_DEBUG) printf(" open");
	fprintf(fp,"\n");
	if (opts & OPT_PORT) {
		fprintf(fp,"void open_%s_cursor(long *sqlcode",prefix);
		if (key_list) {
			fprintf(fp,",");
			cur_key = key_list;
			while(cur_key) {
				fprintf(fp,"%s ",cur_key->key_type);
				if (cur_key->is_ptr) fprintf(fp,"*");
				fprintf(fp,"%s",cur_key->key_name);
				if (cur_key->next) fprintf(fp,",");
				cur_key = cur_key->next;
			}
		}
		fprintf(fp,") {\n");
	}
	else {
		fprintf(fp,"int open_%s_cursor(",prefix);
		if (key_list) {
			cur_key = key_list;
			while(cur_key) {
				fprintf(fp,"%s ",cur_key->key_type);
				if (cur_key->is_ptr) fprintf(fp,"*");
				fprintf(fp,"%s",cur_key->key_name);
				if (cur_key->next) fprintf(fp,",");
				cur_key = cur_key->next;
			}
		}
		else
			fprintf(fp,"void");
		fprintf(fp,") {\n");
	}
	fprintf(fp,"\tsql_return_code = 0;\n");
	fprintf(fp,"\tEXEC SQL DECLARE %s_cursor CURSOR FOR \\\n",
		prefix);
	fprintf(fp,"\t\tSELECT ");
	cur_field = field_list;
	line[0] = 0;
	while(cur_field) {
		strcat(line,cur_field->field_name);
		if (cur_field->next) strcat(line,",");
		if (strlen(line) > 40) {
			fprintf(fp,"%s \\\n",line);
			if (cur_field->next)
				strcpy(line,"\t\t\t");
			else
				line[0] = 0;
		}
		cur_field = cur_field->next;
	}
	if (strlen(line)) fprintf(fp,"%s \\\n",line);
	fprintf(fp,"\t\tFROM %s",table_name);
	if (key_list) {
		fprintf(fp," \\\n\t\tWHERE ");
		line[0] = 0;
		cur_key = key_list;
		while(cur_key) {
			strcat(line,cur_key->key_name);
			strcat(line," = :");
			strcat(line,cur_key->key_name);
			if (cur_key->next)
				strcat(line," AND ");
			else
				strcat(line,";");
			if (strlen(line) > 40) {
				fprintf(fp,"%s",line);
				if (cur_key->next) {
					fprintf(fp," \\\n");
					strcpy(line,"\t\t\t");
				}
				else {
					fprintf(fp,"\n");
					line[0] = 0;
				}
			}
			cur_key = cur_key->next;
		}
		if (strlen(line)) fprintf(fp,"%s\n",line);
	}
	else
		fprintf(fp,";\n");
	if (opts & OPT_PORT) {
		fprintf(fp,"\tif (sql_return_code != 0) {\n");
		fprintf(fp,"\t\t*sqlcode = sql_return_code;\n");
		fprintf(fp,"\t\treturn;\n");
		fprintf(fp,"\t}\n");
	}
	else
		fprintf(fp,"\tif (sql_return_code != 0) return 1;\n");
	fprintf(fp,"\tEXEC SQL OPEN %s_cursor;\n",prefix);
	if (opts & OPT_PORT) {
		fprintf(fp,"\t*sqlcode = sql_return_code;\n");
		fprintf(fp,"\treturn;\n");
	}
	else
		fprintf(fp,"\treturn (sql_return_code == 0 ? 0 : 1);\n");
	fprintf(fp,"}\n");

	/* Write the fetch function */
	if (opts & OPT_DEBUG) printf(" fetch");
	fprintf(fp,"\n");
	if (opts & OPT_PORT)
		fprintf(fp,
			"void fetch_%s_record(long *sqlcode,%s_REC *rec) {\n",
			prefix,stredit(prefix,"UPCASE"));
	else
		fprintf(fp,"int fetch_%s_record(%s_REC *rec) {\n",
			prefix,stredit(prefix,"UPCASE"));
	fprintf(fp,"\tsql_return_code = 0;\n");
	fprintf(fp,"\tEXEC SQL FETCH %s_cursor INTO :rec;\n",prefix);
	/* Check to see if the table has any strings */
	has_string = 0;
	cur_field = field_list;
	while(cur_field) {
		if (cur_field->field_type == FT_STRING) {
			has_string = 1;
			break;
		}
		cur_field = cur_field->next;
	}
	if (has_string) {
		fprintf(fp,"\tif (sql_return_code == 0) {\n");
		cur_field = field_list;
		while(cur_field) {
			if (cur_field->field_type == FT_STRING)
				fprintf(fp,"\t\ttrim(rec->%s);\n",
					cur_field->field_name);
			cur_field = cur_field->next;
		}
		fprintf(fp,"\t}\n");
	}
	if (opts & OPT_PORT) {
		fprintf(fp,"\t*sqlcode = sql_return_code;\n");
		fprintf(fp,"\treturn;\n");
	}
	else
		fprintf(fp,"\treturn (sql_return_code == 0 ? 0 : 1);\n");
	fprintf(fp,"}\n");

	/* Write the close function */
	if (opts & OPT_DEBUG) printf(" close");
	fprintf(fp,"\n");
	if (opts & OPT_PORT)
		fprintf(fp,"void close_%s_cursor(long *sqlcode) {\n",prefix);
	else
		fprintf(fp,"int close_%s_cursor(void) {\n",prefix);
	fprintf(fp,"\tsql_return_code = 0;\n");
	fprintf(fp,"\tEXEC SQL CLOSE %s_cursor;\n",prefix);
	if (opts & OPT_PORT) {
		fprintf(fp,"\t*sqlcode = sql_return_code;\n");
		fprintf(fp,"\treturn;\n");
	}
	else
		fprintf(fp,"\treturn (sql_return_code == 0 ? 0 : 1);\n");
	fprintf(fp,"}\n");

	if (strlen(seq_name)) {
		/* Write the get id function */
		if (opts & OPT_DEBUG) printf(" get_id");
		fprintf(fp,"\n");
		if (opts & OPT_PORT)
			fprintf(fp,"void get_%s_id(long *sqlcode,%s *id) {\n",
				prefix,ID_TYPE_STRING);
		else
			fprintf(fp,"int get_%s_id(%s *id) {\n",
				prefix,ID_TYPE_STRING);
		fprintf(fp,"\tsql_return_code = 0;\n");
		fprintf(fp,"\tEXEC SQL SELECT %s.NEXTVAL ",seq_name);
		fprintf(fp,"INTO :id FROM dual;\n");
		if (opts & OPT_PORT) {
			fprintf(fp,"\t*sqlcode = sql_return_code;\n");
			fprintf(fp,"\treturn;\n");
		}
		else
			fprintf(fp,
				"\treturn (sql_return_code == 0 ? 0 : 1);\n");
		fprintf(fp,"}\n");
	}

	if (opts & OPT_INS) {
		/* Write the insert function */
		if (opts & OPT_DEBUG) printf(" insert");
		fprintf(fp,"\n");
		if (opts & OPT_PORT)
			fprintf(fp,
			 "void insert_%s_record(long *sqlcode,%s_REC *rec) {\n",
				prefix,stredit(prefix,"UPCASE"));
		else
			fprintf(fp,"int insert_%s_record(%s_REC *rec) {\n",
				prefix,stredit(prefix,"UPCASE"));
		fprintf(fp,"\tsql_return_code = 0;\n");
		fprintf(fp,"\tEXEC SQL INSERT INTO %s (\n",table_name);
		cur_field = field_list;
		while(cur_field) {
			fprintf(fp,"\t\t%s",cur_field->field_name);
			if (cur_field->next) fprintf(fp,",");
			fprintf(fp,"\n");
			cur_field = cur_field->next;
		}
		fprintf(fp,"\t) VALUES (\n");
		cur_field = field_list;
		while(cur_field) {
			if (cur_field->field_type == FT_DATE) {
				fprintf(fp,"\t\tTO_DATE(:rec->%s,",
					cur_field->field_name);
				fprintf(fp,"'DD-MON-YYYY HH24:MI:SS')");
			}
			else
				fprintf(fp,"\t\t:rec->%s",
					cur_field->field_name);
			if (cur_field->next) fprintf(fp,",");
			fprintf(fp,"\n");
			cur_field = cur_field->next;
		}
		fprintf(fp,"\t);\n");
		if (opts & OPT_PORT) {
			fprintf(fp,"\t*sqlcode = sql_return_code;\n");
			fprintf(fp,"\treturn;\n");
		}
		else
			fprintf(fp,
				"\treturn (sql_return_code == 0 ? 0 : 1);\n");
		fprintf(fp,"}\n");
	}
	if (opts & OPT_DEBUG) printf(".\n");

	/* Close the pc file and return */
	if (opts & OPT_DEBUG) printf("write_pc: done!\n");
	fclose(fp);
	return 0;
}
#endif
