#!/usr/bin/expect -f


#exp_internal 1

set src [lindex $argv 0]
set dst [lindex $argv 1]
set pass [lindex $argv 2]

if {$argc <2} { exit 1 }

#send_user "connecting to $server\n"
set timeout 30
spawn scp $src $dst
sleep 2
expect {
	"(yes/no)? " {
		send "yes\n"
		sleep 1
		exp_continue
	}
	"assword:" {
		send "$pass\n"
	}
}
set timeout -1
expect { "100%" }
exit 0
