#!/bin/bash
if test -z "$1"; then
	echo "usage: chkcons <hostname>"
	exit 1
fi
if test `echo $1 | grep -c '\-c'` -eq 0; then
	cons=`getcons $1 | awk '{ print $1 }'`
	if test "$cons" = "unknown"; then
		echo "unable to find console"
		exit 1
	fi
else
	cons=$1
fi
tmp=/tmp/chkcons.$$
cleanup() {
	rm -f $tmp
	exit 1
}
trap cleanup SIGINT SIGTERM
#echo "Checking console: $cons"
curl -N -s --connect-timeout 10 http://$cons > $tmp
status=$?
if test $status -eq 0; then
	echo "OK"
else
	msg=`cat $tmp`
	test -z "$msg" && msg="error"
	echo $msg
fi
rm -f $tmp
exit $status
