#!/bin/bash
strip_domain() {
        echo $1 | awk '{
                i=index($0,".");
                if (i > 1)
                        print substr($0,1,i-1)
                else
                        print $0;
                endif
        }'
}
get_domain() {
        echo $1 | awk '{
                i=index($0,".");
                if (i > 1)
                        print substr($0,i)
                else
                        print $0;
                endif
        }'
}
h=`host "$1" | grep "has address" | tail -1`
if test `echo "$h" | grep -c "has address"` -eq 1; then
	echo "$h" | awk '{ print $1 }'
	exit 0;
fi
n=`strip_domain "$1"`
for d in uson.usoncology.int usoncology.com dev.iknowmed.com production.iknowmed.com uprd.usoncology.unx ulab.usoncology.unx oc.mckesson.com
do
	h=`host "$n.$d"`
	if test `echo "$h" | grep -c found` -eq 0; then
		echo "$n.$d"
		exit 0;
	fi
done
echo $1
