
/*
*** this file is automatically generated - DO NOT MODIFY
*/

#include <stdio.h>
#include <string.h>
#include "gendb_lanconfig.h"

int lanconfig_fetch(DB *db) {
	SQLRETURN ret;

	dprintf("Fetching data...\n");
	ret = SQLFetch(db->hstmt);
	if (ret == SQL_SUCCESS || ret == SQL_SUCCESS_WITH_INFO) return 0;
	dberr(SQL_HANDLE_STMT,db->hstmt);
	return ret;
}

int lanconfig_fetch_record(DB *db, struct lanconfig_record *rec) {
	SQLRETURN ret;

	if ((ret = lanconfig_fetch(db)) != 0) {
		SQLCloseCursor(db->hstmt);
		return ret;
	}
	memset(rec,0,sizeof(*rec));
	SQLGetData(db->hstmt, 1, SQL_C_SLONG, (SQLPOINTER) &rec->id, sizeof(rec->id), 0);
	SQLGetData(db->hstmt, 2, SQL_C_CHAR, (SQLPOINTER) rec->site, sizeof(rec->site), 0);
	SQLGetData(db->hstmt, 3, SQL_C_CHAR, (SQLPOINTER) rec->modulecell, sizeof(rec->modulecell), 0);
	SQLGetData(db->hstmt, 4, SQL_C_CHAR, (SQLPOINTER) rec->pod, sizeof(rec->pod), 0);
	SQLGetData(db->hstmt, 5, SQL_C_CHAR, (SQLPOINTER) rec->network_segment, sizeof(rec->network_segment), 0);
	SQLGetData(db->hstmt, 6, SQL_C_CHAR, (SQLPOINTER) rec->primary_ip, sizeof(rec->primary_ip), 0);
	SQLGetData(db->hstmt, 7, SQL_C_CHAR, (SQLPOINTER) rec->primary_ip_mask, sizeof(rec->primary_ip_mask), 0);
	SQLGetData(db->hstmt, 8, SQL_C_CHAR, (SQLPOINTER) rec->primary_ip_gateway, sizeof(rec->primary_ip_gateway), 0);
	SQLGetData(db->hstmt, 9, SQL_C_CHAR, (SQLPOINTER) rec->console_ip, sizeof(rec->console_ip), 0);
	SQLGetData(db->hstmt, 10, SQL_C_CHAR, (SQLPOINTER) rec->backup_ip, sizeof(rec->backup_ip), 0);
	SQLGetData(db->hstmt, 11, SQL_C_CHAR, (SQLPOINTER) rec->cluster_intercon_ip, sizeof(rec->cluster_intercon_ip), 0);
	SQLGetData(db->hstmt, 12, SQL_C_CHAR, (SQLPOINTER) rec->heartbeat_ip, sizeof(rec->heartbeat_ip), 0);
	SQLGetData(db->hstmt, 13, SQL_C_CHAR, (SQLPOINTER) rec->virtual_farm, sizeof(rec->virtual_farm), 0);
	dprintf("----------------- lanconfig record -----------------\n");
	dprintf("id                  :  %d\n",rec->id);
	dprintf("site                :  %s\n",rec->site);
	dprintf("modulecell          :  %s\n",rec->modulecell);
	dprintf("pod                 :  %s\n",rec->pod);
	dprintf("network_segment     :  %s\n",rec->network_segment);
	dprintf("primary_ip          :  %s\n",rec->primary_ip);
	dprintf("primary_ip_mask     :  %s\n",rec->primary_ip_mask);
	dprintf("primary_ip_gateway  :  %s\n",rec->primary_ip_gateway);
	dprintf("console_ip          :  %s\n",rec->console_ip);
	dprintf("backup_ip           :  %s\n",rec->backup_ip);
	dprintf("cluster_intercon_ip :  %s\n",rec->cluster_intercon_ip);
	dprintf("heartbeat_ip        :  %s\n",rec->heartbeat_ip);
	dprintf("virtual_farm        :  %s\n",rec->virtual_farm);
	return 0;
}

int lanconfig_select(DB *db, char *clause) {
	char query[4096];
	SQLRETURN ret;

	sprintf(query,"SELECT lanconfig.id,lanconfig.site,lanconfig.modulecell,lanconfig.pod,lanconfig.network_segment,lanconfig.primary_ip,lanconfig.primary_ip_mask,lanconfig.primary_ip_gateway,lanconfig.console_ip,lanconfig.backup_ip,lanconfig.cluster_intercon_ip,lanconfig.heartbeat_ip,lanconfig.virtual_farm FROM lanconfig %s",(clause ? clause : ""));
	dprintf("Executing query: %s\n", query);
	ret = SQLExecDirect(db->hstmt, (SQLCHAR *) query, SQL_NTS);
	if (ret == SQL_SUCCESS || ret == SQL_SUCCESS_WITH_INFO) return 0;
	dberr(SQL_HANDLE_STMT,db->hstmt);
	return ret;
}

int lanconfig_select_record(DB *db, struct lanconfig_record *rec, char *clause) {
	SQLRETURN ret;

	if ((ret = lanconfig_select(db, clause)) != 0) return ret;
	if ((ret = lanconfig_fetch_record(db, rec)) != 0) return ret;
	SQLCloseCursor(db->hstmt);
	return 0;
}

int lanconfig_insert(DB *db, struct lanconfig_record *rec) {
	char query[4096];
	SQLRETURN ret;

	sprintf(query,"INSERT INTO lanconfig (id,site,modulecell,pod,network_segment,primary_ip,primary_ip_mask,primary_ip_gateway,console_ip,backup_ip,cluster_intercon_ip,heartbeat_ip,virtual_farm) VALUES (%d,'%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s')",rec->id,rec->site,rec->modulecell,rec->pod,rec->network_segment,rec->primary_ip,rec->primary_ip_mask,rec->primary_ip_gateway,rec->console_ip,rec->backup_ip,rec->cluster_intercon_ip,rec->heartbeat_ip,rec->virtual_farm);
	dprintf("Executing query: %s\n", query);
	ret = SQLExecDirect(db->hstmt, (SQLCHAR *) query, SQL_NTS);
	if (ret == SQL_SUCCESS || ret == SQL_SUCCESS_WITH_INFO) return 0;
	dberr(SQL_HANDLE_STMT,db->hstmt);
	return ret;
}

int lanconfig_update_record(DB *db, struct lanconfig_record *rec, char *clause) {
	char query[4096];
	SQLRETURN ret;

	sprintf(query,"UPDATE lanconfig SET id = %d,site = '%s',modulecell = '%s',pod = '%s',network_segment = '%s',primary_ip = '%s',primary_ip_mask = '%s',primary_ip_gateway = '%s',console_ip = '%s',backup_ip = '%s',cluster_intercon_ip = '%s',heartbeat_ip = '%s',virtual_farm = '%s'",rec->id,rec->site,rec->modulecell,rec->pod,rec->network_segment,rec->primary_ip,rec->primary_ip_mask,rec->primary_ip_gateway,rec->console_ip,rec->backup_ip,rec->cluster_intercon_ip,rec->heartbeat_ip,rec->virtual_farm);
	if (clause) {
		if (clause[0] != ' ') strcat(query," ");
		strcat(query,clause);
	}
	dprintf("Executing query: %s\n", query);
	ret = SQLExecDirect(db->hstmt, (SQLCHAR *) query, SQL_NTS);
	if (ret == SQL_SUCCESS || ret == SQL_SUCCESS_WITH_INFO) return 0;
	dberr(SQL_HANDLE_STMT,db->hstmt);
	return ret;
}

int lanconfig_delete(DB *db, char *clause) {
	char query[4096];
	SQLRETURN ret;

	sprintf(query,"DELETE FROM lanconfig %s",(clause ? clause : ""));
	dprintf("Executing query: %s\n", query);
	ret = SQLExecDirect(db->hstmt, (SQLCHAR *) query, SQL_NTS);
	if (ret == SQL_SUCCESS || ret == SQL_SUCCESS_WITH_INFO) return 0;
	dberr(SQL_HANDLE_STMT,db->hstmt);
	return ret;
}

