
/*
*** this file is automatically generated - DO NOT MODIFY
*/

#include <stdio.h>
#include <string.h>
#include "gendb_picklists.h"

int picklists_fetch(DB *db) {
	SQLRETURN ret;

	dprintf("Fetching data...\n");
	ret = SQLFetch(db->hstmt);
	if (ret == SQL_SUCCESS || ret == SQL_SUCCESS_WITH_INFO) return 0;
	dberr(SQL_HANDLE_STMT,db->hstmt);
	return ret;
}

int picklists_fetch_record(DB *db, struct picklists_record *rec) {
	SQLRETURN ret;

	if ((ret = picklists_fetch(db)) != 0) {
		SQLCloseCursor(db->hstmt);
		return ret;
	}
	memset(rec,0,sizeof(*rec));
	SQLGetData(db->hstmt, 1, SQL_C_SLONG, (SQLPOINTER) &rec->picklistid, sizeof(rec->picklistid), 0);
	SQLGetData(db->hstmt, 2, SQL_C_CHAR, (SQLPOINTER) rec->picklistname, sizeof(rec->picklistname), 0);
	SQLGetData(db->hstmt, 3, SQL_C_CHAR, (SQLPOINTER) rec->selection, sizeof(rec->selection), 0);
	dprintf("----------------- picklists record -----------------\n");
	dprintf("picklistid          :  %d\n",rec->picklistid);
	dprintf("picklistname        :  %s\n",rec->picklistname);
	dprintf("selection           :  %s\n",rec->selection);
	return 0;
}

int picklists_select(DB *db, char *clause) {
	char query[4096];
	SQLRETURN ret;

	sprintf(query,"SELECT picklists.picklistid,picklists.picklistname,picklists.selection FROM picklists %s",(clause ? clause : ""));
	dprintf("Executing query: %s\n", query);
	ret = SQLExecDirect(db->hstmt, (SQLCHAR *) query, SQL_NTS);
	if (ret == SQL_SUCCESS || ret == SQL_SUCCESS_WITH_INFO) return 0;
	dberr(SQL_HANDLE_STMT,db->hstmt);
	return ret;
}

int picklists_select_record(DB *db, struct picklists_record *rec, char *clause) {
	SQLRETURN ret;

	if ((ret = picklists_select(db, clause)) != 0) return ret;
	if ((ret = picklists_fetch_record(db, rec)) != 0) return ret;
	SQLCloseCursor(db->hstmt);
	return 0;
}

int picklists_insert(DB *db, struct picklists_record *rec) {
	char query[4096];
	SQLRETURN ret;

	sprintf(query,"INSERT INTO picklists (picklistid,picklistname,selection) VALUES (%d,'%s','%s')",rec->picklistid,rec->picklistname,rec->selection);
	dprintf("Executing query: %s\n", query);
	ret = SQLExecDirect(db->hstmt, (SQLCHAR *) query, SQL_NTS);
	if (ret == SQL_SUCCESS || ret == SQL_SUCCESS_WITH_INFO) return 0;
	dberr(SQL_HANDLE_STMT,db->hstmt);
	return ret;
}

int picklists_update_record(DB *db, struct picklists_record *rec, char *clause) {
	char query[4096];
	SQLRETURN ret;

	sprintf(query,"UPDATE picklists SET picklistid = %d,picklistname = '%s',selection = '%s'",rec->picklistid,rec->picklistname,rec->selection);
	if (clause) {
		if (clause[0] != ' ') strcat(query," ");
		strcat(query,clause);
	}
	dprintf("Executing query: %s\n", query);
	ret = SQLExecDirect(db->hstmt, (SQLCHAR *) query, SQL_NTS);
	if (ret == SQL_SUCCESS || ret == SQL_SUCCESS_WITH_INFO) return 0;
	dberr(SQL_HANDLE_STMT,db->hstmt);
	return ret;
}

int picklists_delete(DB *db, char *clause) {
	char query[4096];
	SQLRETURN ret;

	sprintf(query,"DELETE FROM picklists %s",(clause ? clause : ""));
	dprintf("Executing query: %s\n", query);
	ret = SQLExecDirect(db->hstmt, (SQLCHAR *) query, SQL_NTS);
	if (ret == SQL_SUCCESS || ret == SQL_SUCCESS_WITH_INFO) return 0;
	dberr(SQL_HANDLE_STMT,db->hstmt);
	return ret;
}

