
#ifndef __VM_DISKS_H
#define __VM_DISKS_H

/*
*** this file is automatically generated - DO NOT MODIFY
*/

#include "db.h"

/* Structure definition for the vm_disks table */
struct vm_disks_record {
	int vm_id;
	char name[65];
	char filename[257];
	long long size;
	char isthin[17];
};
#define vm_disks_field_count 5
int vm_disks_insert(DB *db, struct vm_disks_record *rec);
int vm_disks_delete(DB *db, char *clause);

#endif /* __VM_DISKS_H */
