
#ifndef __PICKLISTS_H
#define __PICKLISTS_H

/*
*** this file is automatically generated - DO NOT MODIFY
*/

#include "db.h"

/* Structure definition for the picklists table */
struct picklists_record {
	int picklistid;
	char picklistname[51];
	char selection[51];
};
int picklists_fetch(DB *db);
int picklists_fetch_record(DB *db, struct picklists_record *rec);
int picklists_select(DB *db, char *clause);
int picklists_select_record(DB *db, struct picklists_record *rec, char *clause);
int picklists_insert(DB *db, struct picklists_record *rec);
int picklists_update_record(DB *db, struct picklists_record *rec, char *clause);
int picklists_delete(DB *db, char *clause);

#endif /* __PICKLISTS_H */
