
/*
*** this file is automatically generated - DO NOT MODIFY
*/

#include <stdio.h>
#include <string.h>
#include "gendb_vm_disks.h"

int vm_disks_insert(DB *db, struct vm_disks_record *rec) {
#if vm_disks_field_count > 0
	char query[4096];
	SQLRETURN ret;

	sprintf(query,"INSERT INTO vm_disks (vm_id,name,filename,size,isthin) VALUES (%d,'%s','%s',%lld,'%s')",rec->vm_id,rec->name,rec->filename,rec->size,rec->isthin);
	dprintf("Executing query: %s\n", query);
	ret = SQLExecDirect(db->hstmt, (SQLCHAR *) query, SQL_NTS);
	if (ret == SQL_SUCCESS || ret == SQL_SUCCESS_WITH_INFO) return 0;
	ret = dberr(SQL_HANDLE_STMT,db->hstmt,"vm_disks_insert");
	printf("Offending query: %s\n", query);
	return ret;
#else
	return 0;
#endif
}

int vm_disks_delete(DB *db, char *clause) {
#if vm_disks_field_count > 0
	char query[4096];
	SQLRETURN ret;

	sprintf(query,"DELETE FROM vm_disks %s",(clause ? clause : ""));
	dprintf("Executing query: %s\n", query);
	ret = SQLExecDirect(db->hstmt, (SQLCHAR *) query, SQL_NTS);
	if (ret == SQL_SUCCESS || ret == SQL_SUCCESS_WITH_INFO) return 0;
	ret = dberr(SQL_HANDLE_STMT,db->hstmt,"vm_disks_delete");
	return ret;
#else
	return 0;
#endif
}

