
#ifndef __LANCONFIG_H
#define __LANCONFIG_H

/*
*** this file is automatically generated - DO NOT MODIFY
*/

#include "db.h"

/* Structure definition for the lanconfig table */
struct lanconfig_record {
	int id;
	char site[256];
	char modulecell[256];
	char pod[256];
	char network_segment[256];
	char primary_ip[256];
	char primary_ip_mask[256];
	char primary_ip_gateway[256];
	char console_ip[256];
	char backup_ip[256];
	char cluster_intercon_ip[256];
	char heartbeat_ip[256];
	char virtual_farm[256];
};
int lanconfig_fetch(DB *db);
int lanconfig_fetch_record(DB *db, struct lanconfig_record *rec);
int lanconfig_select(DB *db, char *clause);
int lanconfig_select_record(DB *db, struct lanconfig_record *rec, char *clause);
int lanconfig_insert(DB *db, struct lanconfig_record *rec);
int lanconfig_update_record(DB *db, struct lanconfig_record *rec, char *clause);
int lanconfig_delete(DB *db, char *clause);

#endif /* __LANCONFIG_H */
